IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CABECERA_COMPRA_CODIGO_OPERACION') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CABECERA_COMPRA DROP CONSTRAINT FK_CABECERA_COMPRA_CODIGO_OPERACION
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CABECERA_COMPRA_DOCUMENTO') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CABECERA_COMPRA DROP CONSTRAINT FK_CABECERA_COMPRA_DOCUMENTO
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CABECERA_COMPRA_EMPRESA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CABECERA_COMPRA DROP CONSTRAINT FK_CABECERA_COMPRA_EMPRESA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CABECERA_COMPRA_MONEDA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CABECERA_COMPRA DROP CONSTRAINT FK_CABECERA_COMPRA_MONEDA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CABECERA_COMPRA_TIPO_COMPROBANTE') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CABECERA_COMPRA DROP CONSTRAINT FK_CABECERA_COMPRA_TIPO_COMPROBANTE
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CABECERA_VENTA_CODIGO_OPERACION_VENTAS') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CABECERA_VENTA DROP CONSTRAINT FK_CABECERA_VENTA_CODIGO_OPERACION_VENTAS
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CABECERA_VENTA_CODIGO_OPERACION') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CABECERA_VENTA DROP CONSTRAINT FK_CABECERA_VENTA_CODIGO_OPERACION
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CABECERA_VENTA_DOCUMENTO') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CABECERA_VENTA DROP CONSTRAINT FK_CABECERA_VENTA_DOCUMENTO
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CABECERA_VENTA_EMPRESA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CABECERA_VENTA DROP CONSTRAINT FK_CABECERA_VENTA_EMPRESA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CABECERA_VENTA_MONEDA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CABECERA_VENTA DROP CONSTRAINT FK_CABECERA_VENTA_MONEDA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CABECERA_VENTA_PUNTO_VENTA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CABECERA_VENTA DROP CONSTRAINT FK_CABECERA_VENTA_PUNTO_VENTA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CABECERA_VENTA_TIPO_COMPROBANTE') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CABECERA_VENTA DROP CONSTRAINT FK_CABECERA_VENTA_TIPO_COMPROBANTE
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DETALLE_COMPRA_ALICUOTA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DETALLE_COMPRA DROP CONSTRAINT FK_DETALLE_COMPRA_ALICUOTA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DETALLE_COMPRA_CABECERA_COMPRA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DETALLE_COMPRA DROP CONSTRAINT FK_DETALLE_COMPRA_CABECERA_COMPRA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DETALLE_COMPRA_CONCEPTOCPA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DETALLE_COMPRA DROP CONSTRAINT FK_DETALLE_COMPRA_CONCEPTOCPA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DETALLE_VENTA_ALICUOTA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DETALLE_VENTA DROP CONSTRAINT FK_DETALLE_VENTA_ALICUOTA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DETALLE_VENTA_CABECERA_VENTA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DETALLE_VENTA DROP CONSTRAINT FK_DETALLE_VENTA_CABECERA_VENTA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DETALLE_VENTA_CONCEPTO') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DETALLE_VENTA DROP CONSTRAINT FK_DETALLE_VENTA_CONCEPTO
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DETALLE_VENTA_DETALLE_VENTA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DETALLE_VENTA DROP CONSTRAINT FK_DETALLE_VENTA_DETALLE_VENTA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_DETALLE_VENTA_DETALLE_VENTA1') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DETALLE_VENTA DROP CONSTRAINT FK_DETALLE_VENTA_DETALLE_VENTA1
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_PERCEPCION_COMPRA_CABECERA_COMPRA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PERCEPCION_COMPRA DROP CONSTRAINT FK_PERCEPCION_COMPRA_CABECERA_COMPRA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_PERCEPCION_COMPRA_JURISDICCION') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PERCEPCION_COMPRA DROP CONSTRAINT FK_PERCEPCION_COMPRA_JURISDICCION
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_PERCEPCION_COMPRA_TIPO_PERCEPCION') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PERCEPCION_COMPRA DROP CONSTRAINT FK_PERCEPCION_COMPRA_TIPO_PERCEPCION
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_PUNTO_VENTA_EMPRESA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PUNTO_VENTA DROP CONSTRAINT FK_PUNTO_VENTA_EMPRESA
;



IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_BorrarCabeceraDetalleCompras'))
DROP PROCEDURE sp_BorrarCabeceraDetalleCompras
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_BorrarCabeceraDetalleVentas'))
DROP PROCEDURE sp_BorrarCabeceraDetalleVentas
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_crearTMPAsoProFarma'))
DROP PROCEDURE sp_crearTMPAsoProFarma
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_crearTMPI_ALICUOTAS'))
DROP PROCEDURE sp_crearTMPI_ALICUOTAS
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_crearTMPI_VENTAS'))
DROP PROCEDURE sp_crearTMPI_VENTAS
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_ExisteComprobanteDeCompra'))
DROP PROCEDURE sp_ExisteComprobanteDeCompra
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_getEmpresas'))
DROP PROCEDURE sp_getEmpresas
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('SP_IMPORTAAFIP'))
DROP PROCEDURE SP_IMPORTAAFIP
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('SP_IMPORTAASOPROFORMA'))
DROP PROCEDURE SP_IMPORTAASOPROFORMA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_insertCabeceraCompra'))
DROP PROCEDURE sp_insertCabeceraCompra
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_insertCabeceraVenta'))
DROP PROCEDURE sp_insertCabeceraVenta
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_insertConceptoCompra'))
DROP PROCEDURE sp_insertConceptoCompra
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_insertConceptoVenta'))
DROP PROCEDURE sp_insertConceptoVenta
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_insertDetalleCompra'))
DROP PROCEDURE sp_insertDetalleCompra
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_insertDetalleVenta'))
DROP PROCEDURE sp_insertDetalleVenta
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_insertEmpresa'))
DROP PROCEDURE sp_insertEmpresa
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_insertPercepcionCompra'))
DROP PROCEDURE sp_insertPercepcionCompra
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_insertPuntoDeVenta'))
DROP PROCEDURE sp_insertPuntoDeVenta
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('SP_SUBDIARIO_VENTAS_CABECERA'))
DROP PROCEDURE SP_SUBDIARIO_VENTAS_CABECERA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('SP_SUBDIARIO_VENTAS_DETALLE'))
DROP PROCEDURE SP_SUBDIARIO_VENTAS_DETALLE
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_updateConceptoCompra'))
DROP PROCEDURE sp_updateConceptoCompra
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_updateConceptoVenta'))
DROP PROCEDURE sp_updateConceptoVenta
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_updateEmpresa'))
DROP PROCEDURE sp_updateEmpresa
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sp_updatePuntoDeVenta'))
DROP PROCEDURE sp_updatePuntoDeVenta
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('test'))
DROP PROCEDURE test
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ALICUOTA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ALICUOTA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CABECERA_COMPRA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CABECERA_COMPRA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CABECERA_VENTA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CABECERA_VENTA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CODIGO_OPERACION') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CODIGO_OPERACION
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CONCEPTO') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CONCEPTO
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CONCEPTOCPA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CONCEPTOCPA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DETALLE_COMPRA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DETALLE_COMPRA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DETALLE_VENTA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DETALLE_VENTA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DOCUMENTO') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DOCUMENTO
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('EMPRESA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE EMPRESA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('I_ALICUOTAS') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE I_ALICUOTAS
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('I_VENTAS') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE I_VENTAS
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('JURISDICCION') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE JURISDICCION
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('MONEDA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE MONEDA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('PERCEPCION_COMPRA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE PERCEPCION_COMPRA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('PUNTO_VENTA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE PUNTO_VENTA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('TIPO_COMPROBANTE') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE TIPO_COMPROBANTE
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('TIPO_PERCEPCION') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE TIPO_PERCEPCION
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('TMP_ASOPROFARMA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE TMP_ASOPROFARMA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('V_ASIENTOS_COMPRAS') AND OBJECTPROPERTY(id, 'IsView') = 1)
DROP VIEW V_ASIENTOS_COMPRAS
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('V_EXPORTAR_ALICUOTA_COMPRAS') AND OBJECTPROPERTY(id, 'IsView') = 1)
DROP VIEW V_EXPORTAR_ALICUOTA_COMPRAS
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('V_EXPORTAR_ALICUOTA_VENTAS') AND OBJECTPROPERTY(id, 'IsView') = 1)
DROP VIEW V_EXPORTAR_ALICUOTA_VENTAS
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('V_EXPORTAR_CABECERA_COMPRAS') AND OBJECTPROPERTY(id, 'IsView') = 1)
DROP VIEW V_EXPORTAR_CABECERA_COMPRAS
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('V_EXPORTAR_CABECERA_VENTAS') AND OBJECTPROPERTY(id, 'IsView') = 1)
DROP VIEW V_EXPORTAR_CABECERA_VENTAS
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('V_SUBDIARIO_COMPRAS') AND OBJECTPROPERTY(id, 'IsView') = 1)
DROP VIEW V_SUBDIARIO_COMPRAS
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('V_SUBDIARIO_VENTAS') AND OBJECTPROPERTY(id, 'IsView') = 1)
DROP VIEW V_SUBDIARIO_VENTAS
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('V_VENTAS') AND OBJECTPROPERTY(id, 'IsView') = 1)
DROP VIEW V_VENTAS
;


CREATE TABLE ALICUOTA ( 
	ALICUOTA nchar(4) NOT NULL,
	DESCRIPCION varchar(50),
	DEFECTO bit DEFAULT ((0)),
	VISIBLE bit DEFAULT ((0))
)
;

CREATE TABLE CABECERA_COMPRA ( 
	COMPRA_ID numeric(18) identity(1,1)  NOT NULL,
	EMPRESA_ID numeric(11) NOT NULL,
	TIPO_COMPROBANTE_ID nchar(3) NOT NULL,
	TIPO_MONEDA_ID nchar(3) NOT NULL,
	FECHA_IMPUTACION date NOT NULL,
	FECHA_COMPRA date NOT NULL,
	TIPO_DOCUMENTO_ID nchar(2) NOT NULL,
	PUNTO_VENTA nchar(5) NOT NULL,
	NRO_COMPROBANTE nchar(8) NOT NULL,
	VENDEDOR_ID nvarchar(11) NOT NULL,
	RAZON_SOCIAL_VENDEDOR varchar(50) NOT NULL,
	CODIGO_OPERACION_ID nchar(1) NOT NULL,
	TIPO_DE_CAMBIO numeric(10,6) NOT NULL,
	TOTAL_OPERACION numeric(18,2) NOT NULL
)
;

CREATE TABLE CABECERA_VENTA ( 
	VENTA_ID numeric(18) identity(1,1)  NOT NULL,
	EMPRESA_ID numeric(11) NOT NULL,
	TIPO_COMPROBANTE_ID nchar(3) NOT NULL,
	TIPO_MONEDA_ID nchar(3) NOT NULL,
	PUNTO_VENTA_ID int NOT NULL,
	NRO_COMPROBANTE_DESDE nchar(8) NOT NULL,
	NRO_COMPROBANTE_HASTA nchar(8) NOT NULL,
	FECHA_VENTA date NOT NULL,
	TIPO_DOCUMENTO_ID nchar(2) NOT NULL,
	COMPRADOR_ID varchar(13) NOT NULL,
	RAZON_SOCIAL_COMPRADOR varchar(50) NOT NULL,
	CODIGO_OPERACION_ID nchar(1) NOT NULL,
	TIPO_DE_CAMBIO numeric(10,6) DEFAULT ((1)) NOT NULL,
	FECHA_VTO_PAGO date
)
;

CREATE TABLE CODIGO_OPERACION ( 
	CODIGO nchar(1) NOT NULL,
	DESCRIPCION varchar(50),
	DEFECTO bit,
	VISIBLE bit
)
;

CREATE TABLE CONCEPTO ( 
	CODIGO nchar(3) NOT NULL,
	DESCRIPCION varchar(50),
	DEFECTO bit DEFAULT ((1)),
	VISIBLE bit DEFAULT ((1))
)
;

CREATE TABLE CONCEPTOCPA ( 
	CODIGO nchar(3) NOT NULL,
	DESCRIPCION varchar(50) NOT NULL,
	DEFECTO bit DEFAULT ((0)) NOT NULL,
	VISIBLE bit DEFAULT ((1)) NOT NULL
)
;

CREATE TABLE DETALLE_COMPRA ( 
	DETALLE_COMPRA_ID numeric(18) identity(1,1)  NOT NULL,
	CABECERA_COMPRA_ID numeric(18) NOT NULL,
	CONCEPTO_ID nchar(3) NOT NULL,
	ALICUOTA_ID nchar(4) NOT NULL,
	NETO_GRAVADO numeric(18,2) NOT NULL,
	IVA numeric(18,2) NOT NULL,
	EXENTO numeric(18,2) NOT NULL,
	TOTAL numeric(18,2) NOT NULL
)
;

CREATE TABLE DETALLE_VENTA ( 
	DETALLE_VENTA_ID numeric(18) identity(1,1)  NOT NULL,
	CABECERA_VENTA_ID numeric(18),
	CONCEPTO_ID nchar(3) NOT NULL,
	ALICUOTA_ID nchar(4) NOT NULL,
	NETO_GRAVADO numeric(18,2) NOT NULL,
	IVA numeric(18,2) NOT NULL,
	EXENTO numeric(18,2) NOT NULL,
	TOTAL numeric(18,2) NOT NULL
)
;

CREATE TABLE DOCUMENTO ( 
	CODIGO nchar(2) NOT NULL,
	DESCRIPCION nvarchar(50),
	DEFECTO bit DEFAULT ((0)),
	VISIBLE bit DEFAULT ((0))
)
;

CREATE TABLE EMPRESA ( 
	IDENTIFICADOR numeric(11) NOT NULL,
	RAZONSOCIAL varchar(255) NOT NULL,
	VENDEDOR bit DEFAULT ((1)) NOT NULL,
	COMPRADOR bit DEFAULT ((1)) NOT NULL,
	DOMICILIO varchar(255),
	ACTIVO bit DEFAULT ((1)) NOT NULL,
	MONOTRIBUTISTA bit DEFAULT ((0)) NOT NULL
)
;

CREATE TABLE I_ALICUOTAS ( 
	TipoComprobante char(3) NOT NULL,
	PuntoVenta char(5) NOT NULL,
	NumeroComprobante char(20) NOT NULL,
	ImporteNetoGravado char(15) NOT NULL,
	AlicuotaIVA char(4) NOT NULL,
	ImpuestoLiquidado char(15) NOT NULL
)
;

CREATE TABLE I_VENTAS ( 
	FechaComprobante nvarchar(8),
	TipoComprobante nvarchar(3),
	PuntoVenta nvarchar(5),
	NumeroComprobante nvarchar(20),
	NumeroComprobanteHasta nvarchar(20),
	CodigoDocumentoComprador nvarchar(2),
	NumeroIdentificacionComprador nvarchar(20),
	ApellidoNombreComprador nvarchar(30),
	ImporteTotal nvarchar(15),
	ImporteTotalNoNetoGravado nvarchar(15),
	PercecpcionesNoCategoriazados nvarchar(15),
	ImporteExcentas nvarchar(15),
	ImportePercepcionesImpNacionales nvarchar(15),
	ImportePercepcionIIBB nvarchar(15),
	ImportePercepcionesImpMunicipales nvarchar(15),
	ImporteImpuestosInternos nvarchar(15),
	CodigoMoneda nvarchar(3),
	TipoCambio nvarchar(10),
	CantAlicuotasIVA nvarchar(1),
	CodigoOperacion nvarchar(1),
	OtrosTributos nvarchar(15),
	FechaVtoPago nvarchar(8)
)
;

CREATE TABLE JURISDICCION ( 
	CODIGO nchar(2) NOT NULL,
	DESCRIPCION varchar(50) NOT NULL,
	DEFECTO bit DEFAULT ((0)) NOT NULL,
	VISIBLE bit DEFAULT ((1)) NOT NULL
)
;

CREATE TABLE MONEDA ( 
	CODIGO nchar(3) NOT NULL,
	DESCRIPCION varchar(50),
	DEFECTO bit,
	VISIBLE bit DEFAULT ((0))
)
;

CREATE TABLE PERCEPCION_COMPRA ( 
	PERCEPCION_ID numeric(18) identity(1,1)  NOT NULL,
	CABECERA_COMPRA_ID numeric(18) NOT NULL,
	TIPO_PERCEPCION_ID nchar(2) NOT NULL,
	JURISDICCION_ID nchar(2) NOT NULL,
	IMPORTE_PERCEPCION numeric(18,2) NOT NULL
)
;

CREATE TABLE PUNTO_VENTA ( 
	PUNTO_VENTA_ID int identity(1,1)  NOT NULL,
	EMPRESA_ID numeric(11) NOT NULL,
	PUNTO_VENTA nchar(5) NOT NULL,
	ACTIVO bit DEFAULT ((1)) NOT NULL
)
;

CREATE TABLE TIPO_COMPROBANTE ( 
	CODIGO nchar(3) NOT NULL,
	DESCRIPCION nvarchar(50),
	DEFECTO bit DEFAULT ((0)),
	VISIBLE bit DEFAULT ((0)),
	CALCULO char(1) DEFAULT ('D'),
	MULTIPLICADOR int DEFAULT ((1))
)
;

CREATE TABLE TIPO_PERCEPCION ( 
	CODIGO nchar(2) NOT NULL,
	DESCRIPCION varchar(50) NOT NULL,
	DEFECTO bit DEFAULT ((0)) NOT NULL,
	VISIBLE bit NOT NULL
)
;

CREATE TABLE TMP_ASOPROFARMA ( 
	CUIT_DROGUERIA char(11) NOT NULL,
	CUIT_FARMACIA char(11) NOT NULL,
	SUCURSAL char(2) NOT NULL,
	COMPROBANTE char(3) NOT NULL,
	LETRA char(1) NOT NULL,
	PUNTO_VENTA char(4) NOT NULL,
	NUMERO char(8) NOT NULL,
	HOJAS char(2) NOT NULL,
	FECHA_COMPROBANTE char(8) NOT NULL,
	COD_CLIENTE char(8) NOT NULL,
	SUC_CLIENTE char(2) NOT NULL,
	BRUTO_GRAVADO char(15) NOT NULL,
	BRUTO_NO_GRAVADO char(15) NOT NULL,
	DESCUENTO char(15) NOT NULL,
	NETO_GRAVADO char(15) NOT NULL,
	IVA_RI char(15) NOT NULL,
	PERCEPCION_IVA char(15) NOT NULL,
	PERCEPCION_IIBB char(15) NOT NULL,
	IMPUESTO_INTERNO char(15) NOT NULL,
	NETO_NO_GRAVADO char(15) NOT NULL,
	TOTAL char(15) NOT NULL,
	TOTAL_ITEMS char(7) NOT NULL,
	TOTAL_UNIDADES char(7) NOT NULL,
	CAI char(14) NOT NULL,
	VTO_CAI char(8) NOT NULL
)
;


CREATE UNIQUE INDEX IX_CABECERA_VENTA
ON CABECERA_VENTA (EMPRESA_ID ASC, PUNTO_VENTA_ID ASC, TIPO_COMPROBANTE_ID ASC, NRO_COMPROBANTE_DESDE ASC, NRO_COMPROBANTE_HASTA ASC)
;

ALTER TABLE PUNTO_VENTA
	ADD CONSTRAINT IX_PUNTO_VENTA UNIQUE (EMPRESA_ID, PUNTO_VENTA)
;

ALTER TABLE ALICUOTA ADD CONSTRAINT PK_ALICUOTA 
	PRIMARY KEY CLUSTERED (ALICUOTA)
;

ALTER TABLE CABECERA_COMPRA ADD CONSTRAINT PK_CABECERA_COMPRA 
	PRIMARY KEY CLUSTERED (COMPRA_ID)
;

ALTER TABLE CABECERA_VENTA ADD CONSTRAINT PK_CABECERA_VENTA 
	PRIMARY KEY CLUSTERED (VENTA_ID)
;

ALTER TABLE CODIGO_OPERACION ADD CONSTRAINT PK_CODIGO_OPERACION_VENTAS 
	PRIMARY KEY CLUSTERED (CODIGO)
;

ALTER TABLE CONCEPTO ADD CONSTRAINT PK_CONCEPTO 
	PRIMARY KEY CLUSTERED (CODIGO)
;

ALTER TABLE CONCEPTOCPA ADD CONSTRAINT PK_CONCEPTOCPAS 
	PRIMARY KEY CLUSTERED (CODIGO)
;

ALTER TABLE DETALLE_COMPRA ADD CONSTRAINT PK_DETALLE_COMPRA 
	PRIMARY KEY CLUSTERED (DETALLE_COMPRA_ID)
;

ALTER TABLE DETALLE_VENTA ADD CONSTRAINT PK_DETALLE_VENTA 
	PRIMARY KEY CLUSTERED (DETALLE_VENTA_ID)
;

ALTER TABLE DOCUMENTO ADD CONSTRAINT PK_DOCUMENTO 
	PRIMARY KEY CLUSTERED (CODIGO)
;

ALTER TABLE EMPRESA ADD CONSTRAINT PK_EMPRESA 
	PRIMARY KEY CLUSTERED (IDENTIFICADOR)
;

ALTER TABLE JURISDICCION ADD CONSTRAINT PK_JURISDICCION 
	PRIMARY KEY CLUSTERED (CODIGO)
;

ALTER TABLE MONEDA ADD CONSTRAINT PK_MONEDA 
	PRIMARY KEY CLUSTERED (CODIGO)
;

ALTER TABLE PERCEPCION_COMPRA ADD CONSTRAINT PK_PERCEPCION_COMPRA 
	PRIMARY KEY CLUSTERED (PERCEPCION_ID)
;

ALTER TABLE PUNTO_VENTA ADD CONSTRAINT PK_PUNTO_VENTA_1 
	PRIMARY KEY CLUSTERED (PUNTO_VENTA_ID)
;

ALTER TABLE TIPO_COMPROBANTE ADD CONSTRAINT PK_TIPO_COMPROBANTE 
	PRIMARY KEY CLUSTERED (CODIGO)
;

ALTER TABLE TIPO_PERCEPCION ADD CONSTRAINT PK_TIPO_PERCEPCION 
	PRIMARY KEY CLUSTERED (CODIGO)
;



ALTER TABLE CABECERA_COMPRA ADD CONSTRAINT FK_CABECERA_COMPRA_CODIGO_OPERACION 
	FOREIGN KEY (CODIGO_OPERACION_ID) REFERENCES CODIGO_OPERACION (CODIGO)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE CABECERA_COMPRA ADD CONSTRAINT FK_CABECERA_COMPRA_DOCUMENTO 
	FOREIGN KEY (TIPO_DOCUMENTO_ID) REFERENCES DOCUMENTO (CODIGO)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE CABECERA_COMPRA ADD CONSTRAINT FK_CABECERA_COMPRA_EMPRESA 
	FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA (IDENTIFICADOR)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE CABECERA_COMPRA ADD CONSTRAINT FK_CABECERA_COMPRA_MONEDA 
	FOREIGN KEY (TIPO_MONEDA_ID) REFERENCES MONEDA (CODIGO)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE CABECERA_COMPRA ADD CONSTRAINT FK_CABECERA_COMPRA_TIPO_COMPROBANTE 
	FOREIGN KEY (TIPO_COMPROBANTE_ID) REFERENCES TIPO_COMPROBANTE (CODIGO)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE CABECERA_VENTA ADD CONSTRAINT FK_CABECERA_VENTA_CODIGO_OPERACION 
	FOREIGN KEY (CODIGO_OPERACION_ID) REFERENCES CODIGO_OPERACION (CODIGO)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE CABECERA_VENTA ADD CONSTRAINT FK_CABECERA_VENTA_DOCUMENTO 
	FOREIGN KEY (TIPO_DOCUMENTO_ID) REFERENCES DOCUMENTO (CODIGO)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE CABECERA_VENTA ADD CONSTRAINT FK_CABECERA_VENTA_EMPRESA 
	FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA (IDENTIFICADOR)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE CABECERA_VENTA ADD CONSTRAINT FK_CABECERA_VENTA_MONEDA 
	FOREIGN KEY (TIPO_MONEDA_ID) REFERENCES MONEDA (CODIGO)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE CABECERA_VENTA ADD CONSTRAINT FK_CABECERA_VENTA_PUNTO_VENTA 
	FOREIGN KEY (PUNTO_VENTA_ID) REFERENCES PUNTO_VENTA (PUNTO_VENTA_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE CABECERA_VENTA ADD CONSTRAINT FK_CABECERA_VENTA_TIPO_COMPROBANTE 
	FOREIGN KEY (TIPO_COMPROBANTE_ID) REFERENCES TIPO_COMPROBANTE (CODIGO)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE DETALLE_COMPRA ADD CONSTRAINT FK_DETALLE_COMPRA_ALICUOTA 
	FOREIGN KEY (ALICUOTA_ID) REFERENCES ALICUOTA (ALICUOTA)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE DETALLE_COMPRA ADD CONSTRAINT FK_DETALLE_COMPRA_CABECERA_COMPRA 
	FOREIGN KEY (CABECERA_COMPRA_ID) REFERENCES CABECERA_COMPRA (COMPRA_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE DETALLE_COMPRA ADD CONSTRAINT FK_DETALLE_COMPRA_CONCEPTOCPA 
	FOREIGN KEY (CONCEPTO_ID) REFERENCES CONCEPTOCPA (CODIGO)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE DETALLE_VENTA ADD CONSTRAINT FK_DETALLE_VENTA_ALICUOTA 
	FOREIGN KEY (ALICUOTA_ID) REFERENCES ALICUOTA (ALICUOTA)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE DETALLE_VENTA ADD CONSTRAINT FK_DETALLE_VENTA_CABECERA_VENTA 
	FOREIGN KEY (CABECERA_VENTA_ID) REFERENCES CABECERA_VENTA (VENTA_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE DETALLE_VENTA ADD CONSTRAINT FK_DETALLE_VENTA_CONCEPTO 
	FOREIGN KEY (CONCEPTO_ID) REFERENCES CONCEPTO (CODIGO)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE DETALLE_VENTA ADD CONSTRAINT FK_DETALLE_VENTA_DETALLE_VENTA 
	FOREIGN KEY (DETALLE_VENTA_ID) REFERENCES DETALLE_VENTA (DETALLE_VENTA_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE DETALLE_VENTA ADD CONSTRAINT FK_DETALLE_VENTA_DETALLE_VENTA1 
	FOREIGN KEY (DETALLE_VENTA_ID) REFERENCES DETALLE_VENTA (DETALLE_VENTA_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE PERCEPCION_COMPRA ADD CONSTRAINT FK_PERCEPCION_COMPRA_CABECERA_COMPRA 
	FOREIGN KEY (CABECERA_COMPRA_ID) REFERENCES CABECERA_COMPRA (COMPRA_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE PERCEPCION_COMPRA ADD CONSTRAINT FK_PERCEPCION_COMPRA_JURISDICCION 
	FOREIGN KEY (JURISDICCION_ID) REFERENCES JURISDICCION (CODIGO)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE PERCEPCION_COMPRA ADD CONSTRAINT FK_PERCEPCION_COMPRA_TIPO_PERCEPCION 
	FOREIGN KEY (TIPO_PERCEPCION_ID) REFERENCES TIPO_PERCEPCION (CODIGO)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE PUNTO_VENTA ADD CONSTRAINT FK_PUNTO_VENTA_EMPRESA 
	FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA (IDENTIFICADOR)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;
















CREATE VIEW [dbo].[V_ASIENTOS_COMPRAS]
AS

SELECT 
	C.COMPRA_ID,
	E.IDENTIFICADOR,
	E.RAZONSOCIAL,
	X.CONCEPTO,
	FECHA_IMPUTACION,
	FECHA_COMPRA,
	ROUND(DEBE * TP.MULTIPLICADOR * C.TIPO_DE_CAMBIO,2) AS DEBE,
	ROUND(HABER * TP.MULTIPLICADOR * C.TIPO_DE_CAMBIO,2) AS HABER,
	ORDEN
FROM 
(
	
		SELECT     
			CABECERA_COMPRA_ID, 
			'IVA Credito Fiscal' AS CONCEPTO,
			SUM(CASE WHEN D .ALICUOTA_ID IN ( '0005', '0004','0006') THEN D .IVA ELSE 0 END) AS DEBE, 
			0 AS HABER,
			1 AS ORDEN	
		FROM dbo.DETALLE_COMPRA AS D
			GROUP BY CABECERA_COMPRA_ID
		

		UNION ALL
		SELECT     
			CABECERA_COMPRA_ID, 
			'Percep. IVA' AS CONCEPTO,
			SUM(CASE WHEN TIPO_PERCEPCION_ID = '02' THEN IMPORTE_PERCEPCION ELSE 0 END) AS DEBE, 
			0 AS HABER,
			2 AS ORDEN
		FROM dbo.PERCEPCION_COMPRA
			GROUP BY CABECERA_COMPRA_ID
		
		UNION ALL
		SELECT     
			CABECERA_COMPRA_ID, 
			'Percep. Ganancias' AS CONCEPTO,
			SUM(CASE WHEN TIPO_PERCEPCION_ID = '03' THEN IMPORTE_PERCEPCION ELSE 0 END) AS DEBE,
			0 HABER,
			3 AS ORDEN
		FROM dbo.PERCEPCION_COMPRA
			GROUP BY CABECERA_COMPRA_ID
			
		UNION ALL
		SELECT     
			CABECERA_COMPRA_ID, 
			'Percep. IIBB PCIA BS AS' AS CONCEPTO,
			SUM(CASE WHEN TIPO_PERCEPCION_ID = '01' AND JURISDICCION_ID = '01' THEN IMPORTE_PERCEPCION ELSE 0 END) AS DEBE,
			0 HABER,
			4 AS ORDEN
		FROM dbo.PERCEPCION_COMPRA
			GROUP BY CABECERA_COMPRA_ID
		
		UNION ALL
		SELECT     
			CABECERA_COMPRA_ID, 
			'Percep. IIBB CABA' AS CONCEPTO,
			SUM(CASE WHEN TIPO_PERCEPCION_ID = '01' AND JURISDICCION_ID = '02' THEN IMPORTE_PERCEPCION ELSE 0 END) AS DEBE,
			0 HABER,
			5 AS ORDEN
		FROM dbo.PERCEPCION_COMPRA
			GROUP BY CABECERA_COMPRA_ID
	
		UNION ALL
		SELECT     
			CABECERA_COMPRA_ID, 
			'Percepc. IIBB OTRA' AS CONCEPTO,
			SUM(CASE WHEN TIPO_PERCEPCION_ID = '01' AND JURISDICCION_ID = '99' THEN IMPORTE_PERCEPCION ELSE 0 END) AS DEBE,
			0 HABER,
			6 AS ORDEN
		FROM dbo.PERCEPCION_COMPRA
			GROUP BY CABECERA_COMPRA_ID		
	
		UNION ALL
		SELECT     
			CABECERA_COMPRA_ID, 
			'Otra Percepcion' AS CONCEPTO,
			SUM(CASE WHEN TIPO_PERCEPCION_ID NOT IN ('01', '02', '03') THEN IMPORTE_PERCEPCION ELSE 0 END) AS DEBE,
			0 HABER,
			7 AS ORDEN
		FROM dbo.PERCEPCION_COMPRA
			GROUP BY CABECERA_COMPRA_ID	
		
		UNION ALL

		select
			D.CABECERA_COMPRA_ID, 
			CPTO.DESCRIPCION AS CONCEPTO,
			SUM(
				CASE WHEN C.TIPO_COMPROBANTE_ID = '011' THEN ISNULL(D.TOTAL, 0) 
				ELSE ISNULL(D.NETO_GRAVADO,0) + ISNULL(EXENTO,0) END) AS DEBE,
			0 AS HABER,
			8 AS ORDEN
		from 
		dbo.CABECERA_COMPRA C  INNER JOIN
		dbo.DETALLE_COMPRA D  ON C.COMPRA_ID = D.CABECERA_COMPRA_ID INNER JOIN
		dbo.CONCEPTOCPA CPTO ON D.CONCEPTO_ID = CPTO.CODIGO
		GROUP BY CABECERA_COMPRA_ID, CPTO.DESCRIPCION
		

				
		UNION ALL
		SELECT     
			COMPRA_ID AS CABECERA_COMPRA_ID ,
			'A Proveedores' AS CONCEPTO,
			0 AS DEBE,
			TOTAL_OPERACION  AS HABER,
			20 AS ORDEN
		FROM dbo.CABECERA_COMPRA 
			
) AS X INNER JOIN CABECERA_COMPRA C ON X.CABECERA_COMPRA_ID = C.COMPRA_ID
INNER JOIN dbo.TIPO_COMPROBANTE TP ON C.TIPO_COMPROBANTE_ID = TP.CODIGO
INNER JOIN DBO.EMPRESA E ON C.EMPRESA_ID = E.IDENTIFICADOR
WHERE DEBE <> 0 OR HABER <> 0









;











CREATE VIEW [dbo].[V_EXPORTAR_ALICUOTA_COMPRAS]
AS

SELECT 
	C.TIPO_COMPROBANTE_ID AS [Tipo de comprobante],
	REPLACE(STR(PUNTO_VENTA , 5), SPACE(1), '0') AS [Punto de venta],
	REPLACE(STR(C.NRO_COMPROBANTE , 20), SPACE(1), '0') AS [Número de comprobante],
	C.TIPO_DOCUMENTO_ID AS [Codigo de documento del vendedor],
	REPLACE(STR(C.VENDEDOR_ID,20),SPACE(1), '0') as [Numero de identificación del vendedor],
	
	RIGHT('000000000000000' + 
		LEFT(CONVERT(NUMERIC(16,2), ROUND(C.TIPO_DE_CAMBIO *  SUM(D.NETO_GRAVADO), 2) * 100)
		,LEN(CONVERT(NUMERIC(16,2), C.TIPO_DE_CAMBIO * SUM(D.NETO_GRAVADO) * 100)) - 3)
		,15) AS [Importe neto gravado],

	D.ALICUOTA_ID AS [Alicuota de IVA],
	
	RIGHT('000000000000000' + 
		LEFT(CONVERT(NUMERIC(16,2),  ROUND(C.TIPO_DE_CAMBIO * SUM(D.IVA),2) * 100 )
		,LEN(CONVERT(NUMERIC(16,2), C.TIPO_DE_CAMBIO * SUM(D.IVA) * 100)) - 3)
		,15) AS [Impuesto liquidado],


	C.EMPRESA_ID,
	C.FECHA_IMPUTACION
FROM CABECERA_COMPRA C

INNER JOIN DETALLE_COMPRA D ON C.COMPRA_ID = D.CABECERA_COMPRA_ID

WHERE EXISTS (SELECT 1 FROM EMPRESA E WHERE C.EMPRESA_ID = E.IDENTIFICADOR AND E.MONOTRIBUTISTA = 0)
	AND C.TIPO_COMPROBANTE_ID IN ('001','002','003','004','005','081','112','115')
	--GG 06.01.17 (COMENTE EL CODIGO DE ALICUTA)
	--AND D.ALICUOTA_ID <> '0003'
GROUP BY 
	C.TIPO_COMPROBANTE_ID ,
	REPLACE(STR(PUNTO_VENTA , 5), SPACE(1), '0') ,
	REPLACE(STR(C.NRO_COMPROBANTE , 20), SPACE(1), '0'),
	C.TIPO_DOCUMENTO_ID,
	REPLACE(STR(C.VENDEDOR_ID,20),SPACE(1), '0'),
	D.ALICUOTA_ID,
	C.EMPRESA_ID,
	C.FECHA_IMPUTACION,
	C.TIPO_DE_CAMBIO












;











CREATE VIEW [dbo].[V_EXPORTAR_ALICUOTA_VENTAS]
AS

SELECT 
	C.TIPO_COMPROBANTE_ID AS [TIPO DE COMPROBANTE],
	REPLACE(STR(PUNTO_VENTA , 5), SPACE(1), '0') AS [Punto de Venta],
	REPLACE(STR(C.NRO_COMPROBANTE_DESDE , 20), SPACE(1), '0') AS [Comprobante Desde],

	RIGHT('000000000000000' + 
		LEFT(CONVERT(NUMERIC(16,2),  ROUND(C.TIPO_DE_CAMBIO * SUM(D.NETO_GRAVADO),2) * 100 )
		, LEN(CONVERT(NUMERIC(16,2), C.TIPO_DE_CAMBIO * SUM(D.NETO_GRAVADO ) * 100)) - 3)
		,15) AS [Neto Gravado],
	
	D.ALICUOTA_ID AS [Codigo Alicuota],

	RIGHT('000000000000000' + 
		LEFT(CONVERT(NUMERIC(16,2),  ROUND(C.TIPO_DE_CAMBIO * SUM(D.IVA),2) * 100) 
		,LEN(CONVERT(NUMERIC(16,2), C.TIPO_DE_CAMBIO * SUM(D.IVA) * 100)) - 3),15) AS [IVA],
	C.EMPRESA_ID,
	C.FECHA_VENTA
FROM CABECERA_VENTA C

INNER JOIN DETALLE_VENTA D ON C.VENTA_ID = D.CABECERA_VENTA_ID
INNER JOIN PUNTO_VENTA AS PV ON C.PUNTO_VENTA_ID = PV.PUNTO_VENTA_ID 
WHERE 
	D.CONCEPTO_ID <> '999' AND 
    0 = 
	CASE WHEN D.ALICUOTA_ID ='0003' THEN
		(SELECT COUNT(*) FROM  DETALLE_VENTA DV WHERE D.CABECERA_VENTA_ID= DV.CABECERA_VENTA_ID AND ALICUOTA_ID <> '0003')
	ELSE 0 END
--WHERE D.ALICUOTA_ID	<> CASE WHEN TIPO_COMPROBANTE_ID NOT IN ('019','020','021') THEN '0003' ELSE '0000' END
GROUP BY 
	C.TIPO_COMPROBANTE_ID ,
	REPLACE(STR(PUNTO_VENTA , 5), SPACE(1), '0') ,
	REPLACE(STR(C.NRO_COMPROBANTE_DESDE , 20), SPACE(1), '0'),
	D.ALICUOTA_ID,
	C.EMPRESA_ID,
	C.FECHA_VENTA,
	C.TIPO_DE_CAMBIO









;














CREATE VIEW [dbo].[V_EXPORTAR_CABECERA_COMPRAS]
AS
SELECT
	CONVERT(VARCHAR(12),C.FECHA_COMPRA,112) AS [Fecha de Comprobante],
	C.TIPO_COMPROBANTE_ID AS [Tipo de Comprobante],
	REPLACE(STR(PUNTO_VENTA , 5), SPACE(1), '0') AS [Punto de Venta],
	REPLACE(STR(C.NRO_COMPROBANTE , 20), SPACE(1), '0') AS [Comprobante],
	'                ' AS [Despacho Importacion],
	C.TIPO_DOCUMENTO_ID AS [Codigo Documento Vendedor],
	REPLACE(STR(C.VENDEDOR_ID,20),SPACE(1), '0') AS [Numero ID Vendedor],
	CAST(C.RAZON_SOCIAL_VENDEDOR AS CHAR(30))  AS [Denominacion Vendedor],
    
	
	RIGHT('000000000000000' + 
		LEFT( CONVERT(NUMERIC(16,2), ROUND(C.TOTAL_OPERACION * C.TIPO_DE_CAMBIO ,2) * 100)
		,LEN( CONVERT(NUMERIC(16,2), C.TOTAL_OPERACION * C.TIPO_DE_CAMBIO * 100)) - 3)
		,15) AS [Total Operacion],

    --Para los comprobantes B o C los campos Conceptos que no Integran el Precio Neto Gravado, Importes Operaciones Exentas e Importe Neto Gravado deben ser igual a cero
    RIGHT('000000000000000' + '0',15) AS [Total No Gravados], --Conceptos que no Integran el Precio Neto Gravado
    
	CASE WHEN C.TIPO_COMPROBANTE_ID IN ('001','002','003','004','005','081','112','115') THEN
		RIGHT('000000000000000' + 
			LEFT(CONVERT(NUMERIC(16,2),  ROUND(CD.EXENTO * C.TIPO_DE_CAMBIO,2) * 100)
			,LEN(CONVERT(NUMERIC(16,2),  CD.EXENTO * C.TIPO_DE_CAMBIO * 100)) - 3)
			,15) 
		ELSE 
			RIGHT('000000000000000' + '0',15)
		END AS [Importe Operaciones Exentas], -- Importes Operaciones Exentas

    RIGHT('000000000000000' + 
		LEFT(CONVERT(NUMERIC(16,2),  ROUND(ISNULL(P.IVA,0) * C.TIPO_DE_CAMBIO,2) * 100) 
		,LEN(CONVERT(NUMERIC( 16,2), ISNULL(P.IVA,0) * C.TIPO_DE_CAMBIO * 100)) - 3)
		,15) AS [Percepcion IVA],

    --RIGHT('000000000000000' + LEFT(CONVERT(VARCHAR(16),  ISNULL(P.NACIONALES,0) * 100), LEN(CONVERT(VARCHAR(16), ISNULL(P.NACIONALES ,0)* 100)) - 3),15) AS [Percepcion Imp. Nacionales],	
    --HABLAR CON MARCELO POR SI GANANCIAS NO ES CONSIDERADO UN IMPUESTO NACIONAL
    RIGHT('000000000000000' + 
		LEFT(CONVERT(NUMERIC(16,2),  ROUND(C.TIPO_DE_CAMBIO *  ( ISNULL(P.NACIONALES,0)  + ISNULL(P.GCIAS,0) ) ,2) * 100)
		,LEN(CONVERT(NUMERIC(16,2),  C.TIPO_DE_CAMBIO * ( ISNULL(P.NACIONALES ,0) + ISNULL(P.GCIAS,0) ) * 100 )) - 3)
		,15) AS [Percepcion Imp. Nacionales],	

    RIGHT('000000000000000' + 
		LEFT(CONVERT(NUMERIC(16,2),  ROUND(C.TIPO_DE_CAMBIO *  ISNULL(P.IIBB,0), 2) * 100 )
		,LEN(CONVERT(NUMERIC(16,2),  C.TIPO_DE_CAMBIO * ISNULL(P.IIBB,0) * 100 )) - 3)
		,15) AS [Percepcion IIBB],


    RIGHT('000000000000000' + 
		LEFT(CONVERT(NUMERIC(16,2),  ROUND(C.TIPO_DE_CAMBIO * ISNULL(P.MUNICIPALES,0), 2) * 100)
		,LEN(CONVERT(NUMERIC(16,2),  C.TIPO_DE_CAMBIO * ISNULL(P.MUNICIPALES,0) * 100 )) - 3)
		,15) AS [Percepcion Imp. Municipales],
    
	
	RIGHT('000000000000000' + '0',15) AS [Importe Impuestos Internos],

    C.TIPO_MONEDA_ID as [Codigo de Moneda],

    RIGHT('0000000000' + 
		LEFT(CONVERT(VARCHAR(17),  C.TIPO_DE_CAMBIO * 1000000), LEN(CONVERT(VARCHAR(17), C.TIPO_DE_CAMBIO * 1000000)) - 7)
		,10) AS [Tipo de Cambio],

    CASE WHEN C.TIPO_COMPROBANTE_ID IN ('001','002','003','004','005','081','112','115') THEN
		ISNULL(cd.CANT_ALICUOTAS,1) 
	else 0 end as [Cant de Alicuotas],
	
	--GG 06.01.2017 (CAMBIO EL CODIGO DE OPERACION SI TIENE UNA ALICUOTA 003
	CASE WHEN EXISTS (SELECT 1 FROM DETALLE_COMPRA DDCC
					  WHERE DDCC.CABECERA_COMPRA_ID = C.COMPRA_ID	
					  AND DDCC.ALICUOTA_ID = '0003') AND C.CODIGO_OPERACION_ID='0'
		THEN 'N' ELSE  C.CODIGO_OPERACION_ID END CODIGO_OPERACION_ID,
	
	
	
	RIGHT('000000000000000' + '0',15) AS [Credito Fiscal Computable],
	RIGHT('000000000000000' + '0',15) AS [Otros Tributos],
	RIGHT('000000000000000' + '0',11) AS [CUIT emisor/corredor],
	'                              ' AS [Denominación del emisor/corredor],
	RIGHT('000000000000000' + '0',15) AS [IVA comisión],
    C.EMPRESA_ID,
    C.FECHA_IMPUTACION
    FROM
    
    dbo.CABECERA_COMPRA AS C LEFT JOIN                
	(SELECT 
		C.COMPRA_ID, 
		SUM(D.TOTAL) AS TOTAL,
		SUM(D.EXENTO) AS EXENTO,	
			(SELECT 
				COUNT( DISTINCT ALICUOTA_ID) 
			FROM DETALLE_COMPRA DDCC
			WHERE DDCC.CABECERA_COMPRA_ID = C.COMPRA_ID  
			--GG 06.01.2017 (COMENTE EL CODIGO DE ALICUOTA)
			--AND DDCC.ALICUOTA_ID <> '0003'
			GROUP BY DDCC.CABECERA_COMPRA_ID ) AS CANT_ALICUOTAS
		FROM 
			dbo.CABECERA_COMPRA AS C INNER JOIN
			dbo.DETALLE_COMPRA AS D ON C.COMPRA_ID = D.CABECERA_COMPRA_ID 
		WHERE C.TIPO_COMPROBANTE_ID IN ('001','002','003','004','005','081','112','115')
		GROUP BY 
			C.COMPRA_ID      
	) CD   
	ON C.COMPRA_ID = CD.COMPRA_ID 
	LEFT JOIN
	(SELECT     
		CABECERA_COMPRA_ID, 
		SUM(IMPORTE_PERCEPCION) AS [Total Percepciones], 
		SUM(CASE WHEN TIPO_PERCEPCION_ID = '01' THEN IMPORTE_PERCEPCION ELSE 0 END) AS IIBB,  
        SUM(CASE WHEN TIPO_PERCEPCION_ID = '02' THEN IMPORTE_PERCEPCION ELSE 0 END) AS IVA, 
        SUM(CASE WHEN TIPO_PERCEPCION_ID = '03' THEN IMPORTE_PERCEPCION ELSE 0 END) AS GCIAS, 
        SUM(CASE WHEN TIPO_PERCEPCION_ID = '04' THEN IMPORTE_PERCEPCION ELSE 0 END) AS MUNICIPALES,
        SUM(CASE WHEN TIPO_PERCEPCION_ID = '05' THEN IMPORTE_PERCEPCION ELSE 0 END) AS NACIONALES,
        SUM(CASE WHEN TIPO_PERCEPCION_ID NOT IN ('01', '02', '03','04','05') THEN IMPORTE_PERCEPCION ELSE 0 END) AS [OTRA PERCEPCION]
    FROM dbo.PERCEPCION_COMPRA
		GROUP BY CABECERA_COMPRA_ID
	) P 
	ON C.COMPRA_ID = P.CABECERA_COMPRA_ID 
	
	--LA EMPRESA NO TIENE QUE SER MONOTRIBUTISTA
	WHERE EXISTS (SELECT 1 FROM EMPRESA E WHERE C.EMPRESA_ID = E.IDENTIFICADOR AND E.MONOTRIBUTISTA = 0)
	
	    













;


















CREATE VIEW [dbo].[V_EXPORTAR_CABECERA_VENTAS]
AS
SELECT

	CONVERT(VARCHAR(12),C.FECHA_VENTA,112) AS [Fecha de Comprobante],
	C.TIPO_COMPROBANTE_ID AS [TIPO DE COMPROBANTE],
	REPLACE(STR(PUNTO_VENTA , 5), SPACE(1), '0') AS [Punto de Venta],
    REPLACE(STR(C.NRO_COMPROBANTE_DESDE , 20), SPACE(1), '0') AS [Comprobante Desde],
	REPLACE(STR(C.NRO_COMPROBANTE_HASTA , 20), SPACE(1), '0') AS [Comprobante Hasta],
	C.TIPO_DOCUMENTO_ID AS [Codigo Documento Comprador], 
    REPLACE(STR(C.COMPRADOR_ID,20),SPACE(1), '0') AS [Numero ID Comprador],
    case when C.TIPO_COMPROBANTE_ID in ('082') and C.TIPO_DOCUMENTO_ID  = '99' then
		CAST('VENTA GLOBAL DIARIA' AS CHAR(30)) 
    else 
    
		CAST(C.RAZON_SOCIAL_COMPRADOR AS CHAR(30)) 
    end AS [Denominacion Comprador],
    RIGHT('000000000000000' + LEFT(CONVERT(VARCHAR(16),  CD.TOTAL * 100), LEN(CONVERT(VARCHAR(16), CD.TOTAL * 100)) - 3),15) AS [Total Operacion],
    RIGHT('000000000000000' + '0',15) AS [Total No Gravados],
    RIGHT('000000000000000' + '0',15) AS [Percepcion No Categorizados],
    RIGHT('000000000000000' + LEFT(CONVERT(VARCHAR(16),  CD.EXENTO * 100), LEN(CONVERT(VARCHAR(16), CD.EXENTO * 100)) - 3),15) AS [Importe Operaciones Exentas],
    RIGHT('000000000000000' + '0',15) AS [Percepciones Impuestos nacionales],
    RIGHT('000000000000000' + '0',15) AS [Percepciones IIBB],
    RIGHT('000000000000000' + '0',15) AS [Percepciones Impuestos Municipales],
	RIGHT('000000000000000' + '0',15) AS [Percepciones Impuestos Internos],
	TIPO_MONEDA_ID,
	RIGHT('0000000000' + LEFT(CONVERT(VARCHAR(17),  C.TIPO_DE_CAMBIO * 1000000), LEN(CONVERT(VARCHAR(17), C.TIPO_DE_CAMBIO * 1000000)) - 7),10) AS [Tipo de Cambio],
	ISNULL(CD.CANT_ALICUOTAS,1) as [Cantidad Alicuotas de IVA],
	C.CODIGO_OPERACION_ID AS [Codigo de Operacion],
	RIGHT('000000000000000' + '0',15) AS [Otros Tributos],
	CASE WHEN C.FECHA_VTO_PAGO IS NULL THEN '00000000' ELSE CONVERT(VARCHAR(12),C.FECHA_VTO_PAGO,112) END AS [Fecha de Vencimiento Pago],
	--'00000000' AS [Fecha de Vencimiento Pago],
	C.EMPRESA_ID
FROM                
	(SELECT 
		C.VENTA_ID, 
		CONVERT(NUMERIC(16,2),ROUND(SUM(D.TOTAL) * C.TIPO_DE_CAMBIO,2)) AS TOTAL,
		CONVERT(NUMERIC(16,2),ROUND(SUM(D.EXENTO) * C.TIPO_DE_CAMBIO,2)) AS EXENTO,
			(SELECT 
				COUNT( DISTINCT ALICUOTA_ID) 
			FROM DETALLE_VENTA DDVV 
			WHERE DDVV.CABECERA_VENTA_ID = C.VENTA_ID AND DDVV.ALICUOTA_ID <> '0003' 
			GROUP BY DDVV.CABECERA_VENTA_ID ) AS CANT_ALICUOTAS
		FROM 
			dbo.CABECERA_VENTA AS C INNER JOIN
			dbo.DETALLE_VENTA AS D ON C.VENTA_ID = D.CABECERA_VENTA_ID 
		WHERE D.CONCEPTO_ID <> '999'
		GROUP BY 
			C.VENTA_ID ,
			C.TIPO_DE_CAMBIO     
	) CD                      
INNER JOIN 
	dbo.CABECERA_VENTA  AS C ON C.VENTA_ID = CD.VENTA_ID INNER JOIN
    dbo.PUNTO_VENTA AS PV ON C.PUNTO_VENTA_ID = PV.PUNTO_VENTA_ID 








;

















CREATE VIEW [dbo].[V_SUBDIARIO_COMPRAS]
AS
SELECT     
	E.IDENTIFICADOR AS [ID. Comprador], 
	E.RAZONSOCIAL AS [Razon Social Comprador], 
	C.FECHA_COMPRA AS [F. Comprobante], 
    C.FECHA_IMPUTACION AS [F. Imputacion], 
    TP.DESCRIPCION AS [T. Comprobante], 
    C.PUNTO_VENTA + '-' + C.NRO_COMPROBANTE AS Comprobante, 
    TD.DESCRIPCION AS [T. Documento], 
    C.VENDEDOR_ID as [ID. Vendedor], 
    C.RAZON_SOCIAL_VENDEDOR as [Razon Social Vendedor], 
    (ISNULL(D_1.[Total Detalle], 0) + ISNULL(P.[Total Percepciones], 0)) * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS Total,
    M.DESCRIPCION AS Moneda, 
    C.TIPO_DE_CAMBIO AS [T. Cambio],  
    D_1.[NETO GRAVADO 21.00%] * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [Neto Gravado 21.00%], 
    D_1.[NETO GRAVADO 10.5%] * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [Neto Gravado 10.5%], 
    D_1.[NETO GRAVADO 27.0%] * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR  AS [Neto Gravado 27.0%], 
    D_1.[IVA 21.0%] * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [IVA 21.0%], 
    D_1.[IVA 10.5%] * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [IVA 10.5%], 
    D_1.[IVA 27.0%] * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [IVA 27.0%], 
    (D_1.EXENTO + CASE WHEN C.TIPO_COMPROBANTE_ID = '011' THEN (ISNULL(D_1.[Total Detalle], 0) + ISNULL(P.[Total Percepciones], 0)) ELSE 0 END) * C.TIPO_DE_CAMBIO* TP.MULTIPLICADOR  AS EXENTO, 
    ISNULL(P.GCIAS, 0) * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [Perc. Ganancias], 
    ISNULL(P.IVA, 0) * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [Perc. I.V.A], 
    ISNULL(P.[IIBB CABA], 0) * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [Perc. IIBB CABA], 
    ISNULL(P.[IIBB PCIA BS AS], 0) * C.TIPO_DE_CAMBIO  * TP.MULTIPLICADOR AS [Perc IIBB Pcia Bs As], 
    ISNULL(P.[IIBB OTRA], 0) * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [IIBB Otra J],
    ISNULL(P.[OTRA PERCEPCION], 0) * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [Otras Perc],
    C.COMPRA_ID,
	C.TIPO_COMPROBANTE_ID
	,dbo.ConceptosImputados(C.COMPRA_ID) AS Concepto
FROM 
	dbo.CABECERA_COMPRA AS C INNER JOIN
  (SELECT     
		CABECERA_COMPRA_ID, 
		SUM(TOTAL) AS [Total Detalle], 
		SUM(CASE WHEN D .ALICUOTA_ID = '0005' THEN D .NETO_GRAVADO ELSE 0 END) AS [NETO GRAVADO 21.00%], 
		SUM(CASE WHEN D .ALICUOTA_ID = '0004' THEN D .NETO_GRAVADO ELSE 0 END) AS [NETO GRAVADO 10.5%], 
		SUM(CASE WHEN D .ALICUOTA_ID = '0006' THEN D .NETO_GRAVADO ELSE 0 END) AS [NETO GRAVADO 27.0%], 
		SUM(CASE WHEN D .ALICUOTA_ID = '0005' THEN D .IVA ELSE 0 END) AS [IVA 21.0%], 
		SUM(CASE WHEN D .ALICUOTA_ID = '0004' THEN D .IVA ELSE 0 END) AS [IVA 10.5%], 
		SUM(CASE WHEN D .ALICUOTA_ID = '0006' THEN D .IVA ELSE 0 END) AS [IVA 27.0%], 
		SUM(EXENTO) AS EXENTO
	FROM dbo.DETALLE_COMPRA AS D
		GROUP BY CABECERA_COMPRA_ID) AS D_1 ON C.COMPRA_ID = D_1.CABECERA_COMPRA_ID 
	LEFT OUTER JOIN
	(SELECT     
		CABECERA_COMPRA_ID, 
		SUM(IMPORTE_PERCEPCION) AS [Total Percepciones], 
		SUM(CASE WHEN TIPO_PERCEPCION_ID = '01' AND JURISDICCION_ID = '01' THEN IMPORTE_PERCEPCION ELSE 0 END) AS [IIBB PCIA BS AS], 
		SUM(CASE WHEN TIPO_PERCEPCION_ID = '01' AND JURISDICCION_ID = '02' THEN IMPORTE_PERCEPCION ELSE 0 END) AS [IIBB CABA], 
		SUM(CASE WHEN TIPO_PERCEPCION_ID = '01' AND JURISDICCION_ID = '99' THEN IMPORTE_PERCEPCION ELSE 0 END) AS [IIBB OTRA], 
        SUM(CASE WHEN TIPO_PERCEPCION_ID = '02' THEN IMPORTE_PERCEPCION ELSE 0 END) AS IVA, 
        SUM(CASE WHEN TIPO_PERCEPCION_ID = '03' THEN IMPORTE_PERCEPCION ELSE 0 END) AS GCIAS, 
        SUM(CASE WHEN TIPO_PERCEPCION_ID NOT IN ('01', '02', '03') THEN IMPORTE_PERCEPCION ELSE 0 END) AS [OTRA PERCEPCION]
    FROM dbo.PERCEPCION_COMPRA
		GROUP BY CABECERA_COMPRA_ID) AS P ON C.COMPRA_ID = P.CABECERA_COMPRA_ID 
	INNER JOIN
	dbo.DOCUMENTO AS TD ON C.TIPO_DOCUMENTO_ID = TD.CODIGO INNER JOIN
	dbo.EMPRESA AS E ON C.EMPRESA_ID = E.IDENTIFICADOR INNER JOIN
	dbo.MONEDA AS M ON C.TIPO_MONEDA_ID = M.CODIGO INNER JOIN
	dbo.TIPO_COMPROBANTE AS TP ON C.TIPO_COMPROBANTE_ID = TP.CODIGO









;




















CREATE VIEW [dbo].[V_SUBDIARIO_VENTAS]
AS
SELECT     
	E.IDENTIFICADOR AS [ID. Vendedor], 
	E.RAZONSOCIAL AS [Razon Social Vendedor], 
	C.FECHA_VENTA AS [Fecha de Venta], 
	TP.DESCRIPCION AS [Tipo de Comprobante], 
	PV.PUNTO_VENTA + '-' + C.NRO_COMPROBANTE_DESDE AS [Comprobante Desde],
	PV.PUNTO_VENTA + '-' + C.NRO_COMPROBANTE_hasta AS [Comprobante Hasta],
	TD.DESCRIPCION AS [Tipo Documento], 
	C.COMPRADOR_ID AS [ID. Comprador], 
	C.RAZON_SOCIAL_COMPRADOR AS [Razon Social Comprador], 
	M.DESCRIPCION AS [Moneda], 
	C.TIPO_DE_CAMBIO AS [Tipo Cambio],
	SUM(D.TOTAL) * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [Total], 
	SUM(CASE WHEN A.ALICUOTA = '0005' THEN D.NETO_GRAVADO ELSE 0 END) * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [Neto Gravado 21], 
	SUM(CASE WHEN A.ALICUOTA = '0004' THEN D.NETO_GRAVADO ELSE 0 END) * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [Neto Gravado 10.5], 
	SUM(CASE WHEN A.ALICUOTA = '0006' THEN D.NETO_GRAVADO ELSE 0 END) * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [Neto Gravado 27],
	SUM(CASE WHEN A.ALICUOTA = '0005' THEN D .IVA ELSE 0 END) * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [IVA 21.0%], 
	SUM(CASE WHEN A.ALICUOTA = '0004' THEN D .IVA ELSE 0 END) * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [IVA 10.5%],
	SUM(CASE WHEN A.ALICUOTA = '0006' THEN D .IVA ELSE 0 END) * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR [IVA 27.0%], 
	SUM(D.EXENTO) * C.TIPO_DE_CAMBIO * TP.MULTIPLICADOR AS [EXENTO],
	CASE WHEN SUM(D.TOTAL) = 0 THEN 'Comprobante Anulado' else '' end as [ANULADO],
	C.VENTA_ID,
	C.TIPO_COMPROBANTE_ID
                     
FROM         dbo.CABECERA_VENTA AS C INNER JOIN
                      dbo.DETALLE_VENTA AS D ON C.VENTA_ID = D.CABECERA_VENTA_ID INNER JOIN
                      dbo.DOCUMENTO AS TD ON C.TIPO_DOCUMENTO_ID = TD.CODIGO INNER JOIN
                      dbo.EMPRESA AS E ON C.EMPRESA_ID = E.IDENTIFICADOR INNER JOIN
                      dbo.MONEDA AS M ON C.TIPO_MONEDA_ID = M.CODIGO INNER JOIN
                      dbo.PUNTO_VENTA AS PV ON C.PUNTO_VENTA_ID = PV.PUNTO_VENTA_ID INNER JOIN
                      dbo.TIPO_COMPROBANTE AS TP ON C.TIPO_COMPROBANTE_ID = TP.CODIGO INNER JOIN
                      dbo.ALICUOTA AS A ON D.ALICUOTA_ID = A.ALICUOTA INNER JOIN
                      dbo.CONCEPTO AS CP ON D.CONCEPTO_ID = CP.CODIGO
GROUP BY 
	E.IDENTIFICADOR, 
	E.RAZONSOCIAL, 
	C.FECHA_VENTA, 
	TP.DESCRIPCION, 
	PV.PUNTO_VENTA + '-' + C.NRO_COMPROBANTE_DESDE,
	PV.PUNTO_VENTA + '-' + C.NRO_COMPROBANTE_HASTA, 
	TD.DESCRIPCION, 
	C.COMPRADOR_ID, 
	C.RAZON_SOCIAL_COMPRADOR, 
	M.DESCRIPCION,
	C.TIPO_DE_CAMBIO,
	C.VENTA_ID,
	C.TIPO_COMPROBANTE_ID,
	TP.MULTIPLICADOR







;


CREATE VIEW [dbo].[V_VENTAS]
AS
SELECT     
	E.IDENTIFICADOR AS [ID. Vendedor], 
	E.RAZONSOCIAL AS [Razon Social Vendedor], 
	CONVERT(varchar(12),C.FECHA_VENTA,112) AS [Fecha de Venta], 
	TP.CODIGO AS [Cod. Tipo Comprobante], 
	REPLACE(STR(PUNTO_VENTA , 5), SPACE(1), '0') AS [P. DE VENTA],
    REPLACE(STR(C.NRO_COMPROBANTE_DESDE , 20), SPACE(1), '0') AS [Comprobante Desde],
	REPLACE(STR(C.NRO_COMPROBANTE_HASTA , 20), SPACE(1), '0') AS [Comprobante Hasta],
    TD.CODIGO AS [Cod. Tipo Documento], TD.DESCRIPCION AS [Tipo Documento], 
    REPLACE(STR(C.COMPRADOR_ID, 20), SPACE(1), '0')  AS [ID. Comprador],
    CAST(C.RAZON_SOCIAL_COMPRADOR AS CHAR(30))  AS [Razon Social Comprador], CP.CODIGO AS [Cod. Concepto], 
                      CP.DESCRIPCION AS Concepto, M.DESCRIPCION AS Moneda, M.CODIGO AS [Cod .Moneda], D.NETO_GRAVADO, A.ALICUOTA AS [Cod. Alicuota], 
                      A.DESCRIPCION AS Alicuota, D.IVA, D.TOTAL
FROM         dbo.CABECERA_VENTA AS C INNER JOIN
                      dbo.DETALLE_VENTA AS D ON C.VENTA_ID = D.CABECERA_VENTA_ID INNER JOIN
                      dbo.DOCUMENTO AS TD ON C.TIPO_DOCUMENTO_ID = TD.CODIGO INNER JOIN
                      dbo.EMPRESA AS E ON C.EMPRESA_ID = E.IDENTIFICADOR INNER JOIN
                      dbo.MONEDA AS M ON C.TIPO_MONEDA_ID = M.CODIGO INNER JOIN
                      dbo.PUNTO_VENTA AS PV ON C.PUNTO_VENTA_ID = PV.PUNTO_VENTA_ID INNER JOIN
                      dbo.TIPO_COMPROBANTE AS TP ON C.TIPO_COMPROBANTE_ID = TP.CODIGO INNER JOIN
                      dbo.ALICUOTA AS A ON D.ALICUOTA_ID = A.ALICUOTA INNER JOIN
                      dbo.CONCEPTO AS CP ON D.CONCEPTO_ID = CP.CODIGO


;






-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[sp_BorrarCabeceraDetalleCompras]  (@COMPRA_ID AS NUMERIC(18,0))
AS
BEGIN
DECLARE @CANT_REG AS INTEGER
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	
	DELETE FROM PERCEPCION_COMPRA WHERE CABECERA_COMPRA_ID = @COMPRA_ID
	
	
	DELETE FROM DETALLE_COMPRA WHERE CABECERA_COMPRA_ID=@COMPRA_ID
	
	IF @@ROWCOUNT > 0
	BEGIN
		DELETE FROM CABECERA_COMPRA WHERE COMPRA_ID=@COMPRA_ID
	END
	SELECT @CANT_REG = @@ROWCOUNT
	SELECT @CANT_REG
	
END



;

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[sp_BorrarCabeceraDetalleVentas]  (@VENTA_ID AS NUMERIC(13,0))
AS
BEGIN
DECLARE @CANT_REG AS INTEGER
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	DELETE FROM DETALLE_VENTA WHERE CABECERA_VENTA_ID=@VENTA_ID
	
	IF @@ROWCOUNT > 0
	BEGIN
		DELETE FROM CABECERA_VENTA WHERE VENTA_ID =@VENTA_ID
	END
	SELECT @CANT_REG = @@ROWCOUNT
	SELECT @CANT_REG
	
END

;


CREATE PROC [dbo].[sp_crearTMPAsoProFarma](@Datos varchar(255), @formato varchar(255),
@result int OUTPUT, @desResult varchar(255) OUTPUT)
AS BEGIN

	DECLARE @SQL NVARCHAR(255)
	
	SET @SQL =  N'INSERT INTO TMP_ASOPROFARMA SELECT *  FROM  OPENROWSET(BULK ''' + @Datos + ''', FORMATFILE=''' + @formato + ''') AS A'
	BEGIN TRY
		BEGIN TRAN
		DELETE FROM TMP_ASOPROFARMA
		
		EXECUTE sp_executesql @SQL

		COMMIT 
		set @result = 0
		set @desResult ='OK'
	END TRY
	BEGIN CATCH
		ROLLBACK 
		set @result = ERROR_NUMBER()
		set @desResult = ERROR_MESSAGE()
		
	END CATCH

END

;




CREATE PROC [dbo].[sp_crearTMPI_ALICUOTAS](@Datos varchar(255), @formato varchar(255),
@result int OUTPUT, @desResult varchar(255) OUTPUT)
AS BEGIN

	DECLARE @SQL NVARCHAR(255)
	
	SET @SQL =  N'INSERT INTO I_ALICUOTAS SELECT * FROM  OPENROWSET(BULK ''' + @Datos + ''', FORMATFILE=''' + @formato + ''') AS A'
	BEGIN TRY
		BEGIN TRAN
		DELETE FROM I_ALICUOTAS
		
		EXECUTE sp_executesql @SQL

		COMMIT 
		set @result = 0
		set @desResult ='OK'
	END TRY
	BEGIN CATCH
		ROLLBACK 
		set @result = ERROR_NUMBER()
		set @desResult = ERROR_MESSAGE()
		
	END CATCH

END



;




CREATE PROC [dbo].[sp_crearTMPI_VENTAS](@Datos varchar(255), @formato varchar(255),
@result int OUTPUT, @desResult varchar(255) OUTPUT)
AS BEGIN

	DECLARE @SQL NVARCHAR(255)
	
	SET @SQL =  N'INSERT INTO I_VENTAS SELECT * FROM  OPENROWSET(BULK ''' + @Datos + ''', FORMATFILE=''' + @formato + ''') AS A'
	BEGIN TRY
		BEGIN TRAN
		DELETE FROM I_VENTAS
		
		EXECUTE sp_executesql @SQL

		COMMIT 
		set @result = 0
		set @desResult ='OK'
	END TRY
	BEGIN CATCH
		ROLLBACK 
		set @result = ERROR_NUMBER()
		set @desResult = ERROR_MESSAGE()
		
	END CATCH

END



;


-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[sp_ExisteComprobanteDeCompra]
(@VENDEDOR_ID nvarchar(11), @TIPO_COMPROBANTE_ID nvarchar(3), @PUNTO_VENTA nvarchar(5),  @NRO_COMPROBANTE nvarchar(8), @EMPRESA_ID AS NUMERIC(11,0))

AS
BEGIN
	
	SET NOCOUNT ON;

	DECLARE @ROWINSERT INT 
    -- Insert statements for procedure here
	SELECT @ROWINSERT = COUNT(*) FROM CABECERA_COMPRA C WHERE
		C.VENDEDOR_ID = @VENDEDOR_ID
		AND C.TIPO_COMPROBANTE_ID = @TIPO_COMPROBANTE_ID 
		AND C.PUNTO_VENTA = @PUNTO_VENTA 
		AND C.NRO_COMPROBANTE= @NRO_COMPROBANTE
		AND C.EMPRESA_ID = @EMPRESA_ID
	SELECT @ROWINSERT
	
END


;

-- =============================================
-- Author:		<Gerardo Gonzalez Tulian>
-- Create date: <20 de Junio de 2015,,>
-- Description:	<EMPRESAS,,>
-- =============================================
CREATE PROCEDURE [dbo].[sp_getEmpresas]  (@vendedor bit =1,  @comprador bit = 1)
AS
BEGIN
	
	SET NOCOUNT ON;

	SELECT E.IDENTIFICADOR, E.RAZONSOCIAL FROM EMPRESA E WHERE E.VENDEDOR = @vendedor AND E.COMPRADOR = @comprador
END

;









CREATE PROCEDURE [dbo].[SP_IMPORTAAFIP](
	@ID_EMPRESA VARCHAR(13)
 , @CONCEPTO_ID VARCHAR(3)
 , @RESULT INT OUTPUT
 , @DESRESULT VARCHAR(255) OUTPUT

 ) AS 
 BEGIN


DECLARE @TIPO_COMPROBANTE_ID NCHAR(3)
DECLARE @TIPO_MONEDA_ID NCHAR(3)
DECLARE @PUNTO_VENTA_ID INT
DECLARE @NRO_COMPROBANTE_DESDE NCHAR(8)
DECLARE @NRO_COMPROBANTE_HASTA NCHAR(8)
DECLARE @FECHA_VENTA DATE
DECLARE @TIPO_DOCUMENTO_ID NCHAR(2)
DECLARE @COMPRADOR_ID VARCHAR(13)
DECLARE @RAZON_SOCIAL_COMPRADOR VARCHAR(50)
DECLARE @CODIGO_OPERACION_ID NCHAR(1)
DECLARE @TIPO_DE_CAMBIO NUMERIC(10,6)
DECLARE @FECHAVTOPAGO DATE
DECLARE @STRING_FECHAVTOPAGO VARCHAR(8)


DECLARE @ImporteTotal NUMERIC(15,2)
DECLARE @CantAlicuotasIVA INT
DECLARE @NumeroComprobante VARCHAR(20)
DECLARE @PuntoVenta VARCHAR(5)
DECLARE @ImporteExcentas  NUMERIC(15,2)


DECLARE @NETO_GRAVADO NUMERIC(15,2)
DECLARE @ALICUOTA_ID VARCHAR(4)
DECLARE @IVA NUMERIC(15,2)

DECLARE @VENTA_ID INT

DECLARE @FETCH_STATUS INT
DECLARE @CANT_ALICUOTAS INT
DECLARE @ImporteExcentas_insert  NUMERIC(15,2)
DECLARE @ImporteTotal_insert NUMERIC(15,2)


BEGIN TRY
BEGIN TRAN TRANSACCION
	DECLARE CUR CURSOR FAST_FORWARD FOR
	SELECT 
		@ID_EMPRESA
		, TipoComprobante
		, CodigoMoneda
		, PV.PUNTO_VENTA_ID 
		, RIGHT(NumeroComprobante,8)
		, RIGHT(NumeroComprobanteHasta,8)
		, CONVERT("date",FechaComprobante, 105)
		, CodigoDocumentoComprador
		, Right(NumeroIdentificacionComprador, 11)
		, Left(ApellidoNombreComprador, 30)
		, CodigoOperacion
		, CONVERT(NUMERIC(10,6),LEFT(TipoCambio,4)+ '.'+ RIGHT(TipoCambio,6) )
		, CONVERT(NUMERIC(15,2),LEFT(ImporteTotal,13)+'.'+RIGHT(ImporteTotal,2) )
		, CONVERT(INT,CantAlicuotasIVA)
		, NumeroComprobante
		, PuntoVenta 
		, CONVERT(NUMERIC(15,2), LEFT(ImporteExcentas,13)+'.'+RIGHT(ImporteExcentas,2))
		, FechaVtoPago
	FROM I_VENTAS C
	INNER JOIN PUNTO_VENTA PV ON PV.EMPRESA_ID=@ID_EMPRESA AND PV.PUNTO_VENTA= C.PuntoVenta
	--where NumeroComprobante='00000000000000000176'
	OPEN CUR

	FETCH CUR INTO
	@ID_EMPRESA
	,@TIPO_COMPROBANTE_ID 
	,@TIPO_MONEDA_ID 
	,@PUNTO_VENTA_ID 
	,@NRO_COMPROBANTE_DESDE 
	,@NRO_COMPROBANTE_HASTA 
	,@FECHA_VENTA 
	,@TIPO_DOCUMENTO_ID 
	,@COMPRADOR_ID 
	,@RAZON_SOCIAL_COMPRADOR 
	,@CODIGO_OPERACION_ID 
	,@TIPO_DE_CAMBIO 
	,@ImporteTotal 
	,@CantAlicuotasIVA 
	,@NumeroComprobante 
	,@PuntoVenta 
	,@ImporteExcentas
	,@STRING_FECHAVTOPAGO

	SET @FETCH_STATUS  = @@FETCH_STATUS
	WHILE @FETCH_STATUS = 0 BEGIN

		--SELECT
		--@ID_EMPRESA
		--,@TIPO_COMPROBANTE_ID 
		--,@TIPO_MONEDA_ID 
		--,@PUNTO_VENTA_ID 
		--,@NRO_COMPROBANTE_DESDE 
		--,@NRO_COMPROBANTE_HASTA 
		--,@FECHA_VENTA 
		--,@TIPO_DOCUMENTO_ID 
		--,@COMPRADOR_ID 
		--,@RAZON_SOCIAL_COMPRADOR 
		--,@CODIGO_OPERACION_ID 
		--,@TIPO_DE_CAMBIO 
		--,@ImporteTotal 
		--,@CantAlicuotasIVA 
		--,@NumeroComprobante 
		--,@PuntoVenta 
		--,@ImporteExcentas
		--,@CANTALICUOTASIVA

		SET @FECHAVTOPAGO = NULL 
		IF @STRING_FECHAVTOPAGO <> '00000000'
			SET @FECHAVTOPAGO = CONVERT("date",@STRING_FECHAVTOPAGO, 105)

		INSERT INTO [dbo].[CABECERA_VENTA] 
		(EMPRESA_ID
			, TIPO_COMPROBANTE_ID
			, TIPO_MONEDA_ID
			, PUNTO_VENTA_ID
			, NRO_COMPROBANTE_DESDE
			, NRO_COMPROBANTE_HASTA
			, FECHA_VENTA
			, TIPO_DOCUMENTO_ID
			, COMPRADOR_ID
			, RAZON_SOCIAL_COMPRADOR
			, CODIGO_OPERACION_ID
			, TIPO_DE_CAMBIO
			, FECHA_VTO_PAGO)
		VALUES(
			@ID_EMPRESA
			,@TIPO_COMPROBANTE_ID 
			,@TIPO_MONEDA_ID 
			,@PUNTO_VENTA_ID 
			,@NRO_COMPROBANTE_DESDE 
			,@NRO_COMPROBANTE_HASTA 
			,@FECHA_VENTA 
			,@TIPO_DOCUMENTO_ID 
			,@COMPRADOR_ID 
			,@RAZON_SOCIAL_COMPRADOR 
			,@CODIGO_OPERACION_ID 
			,@TIPO_DE_CAMBIO
			,@FECHAVTOPAGO
		)


		SELECT @VENTA_ID = ISNULL(MAX(VENTA_ID),0)  FROM [CABECERA_VENTA]
	

		DECLARE CUR_ALI CURSOR FAST_FORWARD FOR
		SELECT 
			SUM(CONVERT(NUMERIC(15,2), LEFT(ImporteNetoGravado,13)+'.'+RIGHT(ImporteNetoGravado,2)))
			, AlicuotaIVA
			, SUM(CONVERT(NUMERIC(15,2), LEFT(ImpuestoLiquidado,13)+'.'+RIGHT(ImpuestoLiquidado,2)))
			
		FROM I_ALICUOTAS 
		WHERE NumeroComprobante = @NumeroComprobante AND  PuntoVenta = @PuntoVenta and TipoComprobante= @TIPO_COMPROBANTE_ID
		GROUP BY AlicuotaIVA


		/*CUENTO LA CANTIDAD DE ALICUOTAS QUE TIENE EL COMPROBANTE */
		SELECT @CANT_ALICUOTAS = COUNT( distinct AlicuotaIVA)  FROM I_ALICUOTAS 
		WHERE NumeroComprobante = @NumeroComprobante AND  PuntoVenta = @PuntoVenta  and TipoComprobante= @TIPO_COMPROBANTE_ID


		OPEN CUR_ALI

		FETCH CUR_ALI INTO 
		@NETO_GRAVADO 
		,@ALICUOTA_ID 
		,@IVA
		
		WHILE @@FETCH_STATUS = 0 BEGIN
			

			IF @ALICUOTA_ID <> '0003'  BEGIN
				/* Si la ALICUOTA ES <> 0003 tiene NETO_GRAVADO E IVA, para el total realizo el cálculo */
				/* Además si en la única ALICUOTA del comprobante y el comprobante tiene un importe Exento, lo registro */
				set @ImporteExcentas_insert = CASE WHEN @CANT_ALICUOTAS = 1 THEN @ImporteExcentas / @TIPO_DE_CAMBIO ELSE 0 END
				set @ImporteTotal_insert = ((@NETO_GRAVADO + @IVA) / @TIPO_DE_CAMBIO) + CASE WHEN @CANT_ALICUOTAS = 1 THEN @ImporteExcentas / @TIPO_DE_CAMBIO ELSE 0 END
			END ELSE BEGIN
				/* Si la ALICUOTA es = 0003 */
				IF @CANT_ALICUOTAS > 1  BEGIN
					/*Como existen otras alicuotas solo cargo la parte exenta en el renglo de la alicuota*/
					set @ImporteExcentas_insert = CASE WHEN @NETO_GRAVADO = 0 THEN @ImporteExcentas ELSE 0 END / @TIPO_DE_CAMBIO
					set @ImporteTotal_insert = @ImporteExcentas	 / @TIPO_DE_CAMBIO
				END ELSE BEGIN
					/*Como es la unica alicuota y es 003 le cargo el importe total y la parte excenta*/
					--set @ImporteExcentas_insert = (@ImporteTotal + CASE WHEN @NETO_GRAVADO = 0 THEN @ImporteExcentas ELSE 0 END) / @TIPO_DE_CAMBIO
					set @ImporteExcentas_insert = ( CASE WHEN @NETO_GRAVADO = 0 THEN @ImporteExcentas ELSE 0 END) / @TIPO_DE_CAMBIO
					set @ImporteTotal_insert = (@ImporteTotal )	/ @TIPO_DE_CAMBIO
				END
			END		

			SET @NETO_GRAVADO = @NETO_GRAVADO / @TIPO_DE_CAMBIO
			SET @IVA = @IVA / @TIPO_DE_CAMBIO

			INSERT INTO [dbo].[DETALLE_VENTA] (
					CABECERA_VENTA_ID
				, CONCEPTO_ID
				, ALICUOTA_ID
				, NETO_GRAVADO
				, IVA
				, EXENTO
				, TOTAL) 
			VALUES
				(@VENTA_ID
				, @CONCEPTO_ID
				, @ALICUOTA_ID
				, @NETO_GRAVADO
				, @IVA
				, @ImporteExcentas_insert 
				, @ImporteTotal_insert)
			


			FETCH CUR_ALI INTO 
			@NETO_GRAVADO 
			,@ALICUOTA_ID 
			,@IVA 
		END

		CLOSE CUR_ALI
		DEALLOCATE CUR_ALI


		FETCH CUR INTO
		@ID_EMPRESA
		,@TIPO_COMPROBANTE_ID 
		,@TIPO_MONEDA_ID 
		,@PUNTO_VENTA_ID 
		,@NRO_COMPROBANTE_DESDE 
		,@NRO_COMPROBANTE_HASTA 
		,@FECHA_VENTA 
		,@TIPO_DOCUMENTO_ID 
		,@COMPRADOR_ID 
		,@RAZON_SOCIAL_COMPRADOR 
		,@CODIGO_OPERACION_ID 
		,@TIPO_DE_CAMBIO 
		,@ImporteTotal 
		,@CantAlicuotasIVA 
		,@NumeroComprobante 
		,@PuntoVenta 
		,@ImporteExcentas
		,@STRING_FECHAVTOPAGO

		SET @FETCH_STATUS  = @@FETCH_STATUS
	END


	
	--DELETE FROM I_VENTAS
	--DELETE FROM I_ALICUOTAS
	
	SET @RESULT = 0
	SET @DESRESULT = 'OK'
	COMMIT TRAN TRANSACCION

END TRY
BEGIN CATCH
	SET @RESULT = ERROR_NUMBER()
	SET @DESRESULT = ERROR_MESSAGE()
	ROLLBACK TRAN TRANSACCION
	
END CATCH

	CLOSE CUR
	DEALLOCATE CUR

END





;



CREATE PROCEDURE [dbo].[SP_IMPORTAASOPROFORMA](@RESULT INT OUTPUT, @DESRESULT VARCHAR(255) OUTPUT)
AS BEGIN

DECLARE @EMPRESA_ID NUMERIC(11,0)
DECLARE @TIPO_COMPROBANTE_ID VARCHAR(3)
DECLARE @COMPROBANTE VARCHAR(3)
DECLARE @TIPO_MONEDA_ID VARCHAR(3) ='PES'
DECLARE @FECHA_IMPUTACION DATE
DECLARE @FECHA_COMPRA DATE
DECLARE @TIPO_DOCUMENTO_ID VARCHAR(2) = '80'
DECLARE @PUNTO_VENTA VARCHAR(5)
DECLARE @NRO_COMPROBANTE VARCHAR(8)
DECLARE @VENDEDOR_ID varchar(11) --ASOPROFARMA
DECLARE @RAZON_SOCIAL_VENDEDOR VARCHAR(50) ='ASOPROFARMA ASOCIACION PROPIETARIOS DE FARMACIAS'
DECLARE @CODIGO_OPERACION_ID VARCHAR(1) ='0'
DECLARE @TIPO_DE_CAMBIO NUMERIC(10,6) = 1
DECLARE @TOTAL_OPERACION NUMERIC (12,2)
DECLARE @COMPRA_ID NUMERIC(18,0)
DECLARE @ResultSet table (COMPRA_ID NUMERIC(18,0))

--DETALLE DE COMPRA
DECLARE @CONCEPTO_ID VARCHAR(3) = '014' --Mercaderia de Reventa
DECLARE @ALICUOTA_ID VARCHAR(4) --0005 21% , -0003 0%
DECLARE @NETO_GRAVADO NUMERIC(18,2) 
DECLARE @IVA NUMERIC(18,2) 
DECLARE @EXENTO NUMERIC(18,2)
DECLARE @TOTAL NUMERIC(18,2)

--PERCEPCIONES
DECLARE @JURISDICCION_ID VARCHAR(2) --01 -PCIA DE BUENOS AIRES, 00 NO APLICA
DECLARE @TIPO_PERCEPCION_ID VARCHAR(2) --01 -IIBB, 02-IVA
DECLARE @IMPORTE_PERCEPCION NUMERIC(18,2) = 0
DECLARE @PERCEPCION_IVA NUMERIC(18,2) = 0
DECLARE @PERCEPCION_IIBB NUMERIC(18,2) = 0

DECLARE @RETURN INTEGER = 0 



DECLARE CUR CURSOR FOR
	SELECT 
		CUIT_FARMACIA AS EMPRESA_ID													--@EMPRESA_ID
		,CASE COMPROBANTE 
			WHEN  'FAC' THEN '001'									
			WHEN  'NDB' THEN '002'
			WHEN  'NCR' THEN '003'
			ELSE  '000' END AS TIPO_COMPROBANTE_ID									--@TIPO_COMPROBANTE_ID
		,CONVERT(DATE,FECHA_COMPROBANTE) AS FECHA_IMPUTACION						--@FECHA_IMPUTACION
		,CONVERT(DATE,FECHA_COMPROBANTE) AS FECHA_COMPRA							--@FECHA_COMPRA
		,'0' + PUNTO_VENTA AS PUNTO_VENTA											--@PUNTO_VENTA
		,NUMERO AS NRO_COMPROBANTE													--@NRO_COMPROBANTE
		,CUIT_DROGUERIA AS VENDEDOR_ID												--@VENDEDOR_ID
		,CONVERT(NUMERIC(18,2), REPLACE(TOTAL,'-','0')) AS TOTAL_OPERACION			--@TOTAL_OPERACION
		--DETALLE
		,CONVERT(NUMERIC(18,2), REPLACE(NETO_GRAVADO,'-','0')) AS NETO_GRAVADO		--@NETO_GRAVADO
		,CONVERT(NUMERIC(18,2), REPLACE(IVA_RI,'-','0')) AS IVA						--@IVA
		,CONVERT(NUMERIC(18,2), REPLACE(NETO_NO_GRAVADO,'-','0')) as EXENTO			--@EXENTO
		--PERCEPCIONES
		,CONVERT(NUMERIC(18,2), REPLACE(PERCEPCION_IVA,'-','0')) AS PERCEPCION_IVA	--@PERCEPCION_IVA
		,CONVERT(NUMERIC(18,2), REPLACE(PERCEPCION_IIBB,'-','0')) AS PERCEPCION_IIBB--@PERCEPCION_IIBB

	FROM dbo.TMP_ASOPROFARMA

OPEN CUR

BEGIN TRY
	BEGIN TRAN OUTTRAN
	
	FETCH CUR INTO 
		@EMPRESA_ID
		,@TIPO_COMPROBANTE_ID
		,@FECHA_IMPUTACION
		,@FECHA_COMPRA
		,@PUNTO_VENTA
		,@NRO_COMPROBANTE
		,@VENDEDOR_ID
		,@TOTAL_OPERACION
		,@NETO_GRAVADO
		,@IVA
		,@EXENTO
		,@PERCEPCION_IVA
		,@PERCEPCION_IIBB
	WHILE @@FETCH_STATUS = 0 BEGIN

		IF @TIPO_COMPROBANTE_ID <> '000' BEGIN
			SELECT @COMPRA_ID = COMPRA_ID 
			FROM CABECERA_COMPRA C 
			WHERE
				C.VENDEDOR_ID = @VENDEDOR_ID
				AND C.TIPO_COMPROBANTE_ID = @TIPO_COMPROBANTE_ID 
				AND C.PUNTO_VENTA = @PUNTO_VENTA 
				AND C.NRO_COMPROBANTE= @NRO_COMPROBANTE
				AND C.EMPRESA_ID = @EMPRESA_ID
				
			IF @@ROWCOUNT > 0 EXEC dbo.sp_BorrarCabeceraDetalleCompras @COMPRA_ID
			
			SET @CODIGO_OPERACION_ID ='0' 
			
			IF  @EXENTO <> 0  BEGIN
				SET @CODIGO_OPERACION_ID = 'N'
				
			END 
			
			INSERT INTO @ResultSet (COMPRA_ID)	
			EXEC dbo.sp_insertCabeceraCompra 
				@EMPRESA_ID
				,@TIPO_COMPROBANTE_ID
				,@TIPO_MONEDA_ID
				,@FECHA_IMPUTACION
				,@FECHA_COMPRA	
				,@TIPO_DOCUMENTO_ID
				,@PUNTO_VENTA
				,@NRO_COMPROBANTE
				,@VENDEDOR_ID
				,@RAZON_SOCIAL_VENDEDOR
				,@CODIGO_OPERACION_ID
				,@TIPO_DE_CAMBIO
				,@TOTAL_OPERACION
		
			select @COMPRA_ID = COMPRA_ID FROM @ResultSet
			IF @NETO_GRAVADO <> 0 BEGIN
				SET @ALICUOTA_ID = '0005'
				SET @TOTAL = @NETO_GRAVADO + @IVA

				EXEC @RETURN = [dbo].[sp_insertDetalleCompra] @COMPRA_ID, @CONCEPTO_ID, @ALICUOTA_ID, @NETO_GRAVADO, 0, @IVA, @TOTAL
			END
			IF @EXENTO <> 0  BEGIN
				SET @ALICUOTA_ID = '0003'
				SET @IVA = 0
				SET @NETO_GRAVADO = 0
				SET @TOTAL = @EXENTO
				EXEC @RETURN = [dbo].[sp_insertDetalleCompra] @COMPRA_ID, @CONCEPTO_ID, @ALICUOTA_ID,@NETO_GRAVADO, @EXENTO, @IVA, @TOTAL
			END
			
			IF @PERCEPCION_IIBB <> 0 BEGIN
				SET @TIPO_PERCEPCION_ID = '01'
				SET @JURISDICCION_ID = '01'
				SET @IMPORTE_PERCEPCION = @PERCEPCION_IIBB
				EXEC [dbo].[sp_insertPercepcionCompra] @COMPRA_ID,@TIPO_PERCEPCION_ID,@JURISDICCION_ID,@IMPORTE_PERCEPCION
			END

			IF @PERCEPCION_IVA <> 0 BEGIN 
				SET @TIPO_PERCEPCION_ID = '02'
				SET @JURISDICCION_ID = '01'
				SET @IMPORTE_PERCEPCION = @PERCEPCION_IVA
				EXEC [dbo].[sp_insertPercepcionCompra] @COMPRA_ID,@TIPO_PERCEPCION_ID,@JURISDICCION_ID,@IMPORTE_PERCEPCION
			END
		END
		
		
		FETCH CUR INTO 
			@EMPRESA_ID
			,@TIPO_COMPROBANTE_ID
			,@FECHA_IMPUTACION
			,@FECHA_COMPRA
			,@PUNTO_VENTA
			,@NRO_COMPROBANTE
			,@VENDEDOR_ID
			,@TOTAL_OPERACION
			,@NETO_GRAVADO
			,@IVA
			,@EXENTO
			,@PERCEPCION_IVA
			,@PERCEPCION_IIBB
	END
	DELETE FROM TMP_ASOPROFARMA
	COMMIT TRAN OUTTRAN
	SET @RESULT = 0
	SET @DESRESULT = 'OK'
END TRY
BEGIN CATCH
	--SELECT ERROR_NUMBER(), ERROR_MESSAGE(), ERROR_LINE()
	SET @RESULT = ERROR_NUMBER()
	SET @DESRESULT = ERROR_MESSAGE()
	ROLLBACK TRAN OUTTRAN
END CATCH

CLOSE CUR
DEALLOCATE CUR

END 



;




-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[sp_insertCabeceraCompra]
(@EMPRESA_ID numeric(11,0),
 @TIPO_COMPROBANTE_ID as nchar(3),
 @TIPO_MONEDA_ID as nchar(3),
 @FECHA_IMPUTACION as date,
 @FECHA_COMPRA as date,
 @TIPO_DOCUMENTO_ID as nchar(2),
 @PUNTO_VENTA as nchar(5),
 @NRO_COMPROBANTE as nchar(8),
 @VENDEDOR_ID as nchar(11),
 @RAZON_SOCIAL_VENDEDOR as varchar(50),
 @CODIGO_OPERACION_ID as nchar(1),
 @TIPO_DE_CAMBIO AS NUMERIC(10,6),
 @TOTAL_OPERACION AS numeric(18,2)
 )
 
 AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @COMPRA_ID NUMERIC(18,0)
	
	INSERT INTO CABECERA_COMPRA
	( EMPRESA_ID,  TIPO_COMPROBANTE_ID,  TIPO_MONEDA_ID,  FECHA_IMPUTACION,  FECHA_COMPRA,  TIPO_DOCUMENTO_ID,  PUNTO_VENTA,  NRO_COMPROBANTE,  VENDEDOR_ID,  RAZON_SOCIAL_VENDEDOR,  CODIGO_OPERACION_ID,  TIPO_DE_CAMBIO,  TOTAL_OPERACION)
	VALUES
    (@EMPRESA_ID, @TIPO_COMPROBANTE_ID, @TIPO_MONEDA_ID, @FECHA_IMPUTACION, @FECHA_COMPRA, @TIPO_DOCUMENTO_ID, @PUNTO_VENTA, @NRO_COMPROBANTE, @VENDEDOR_ID, @RAZON_SOCIAL_VENDEDOR, @CODIGO_OPERACION_ID, @TIPO_DE_CAMBIO, @TOTAL_OPERACION)
	
	
	SELECT @COMPRA_ID = MAX(COMPRA_ID) FROM CABECERA_COMPRA
	SELECT @COMPRA_ID
END




;


-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[sp_insertCabeceraVenta]
(@EMPRESA_ID numeric(11,0),
 @TIPO_COMPROBANTE_ID as nchar(3),
 @TIPO_MONEDA_ID as nchar(3),
 @PUNTO_VENTA_ID as integer,
 @NRO_COMPROBANTE_DESDE as nchar(8),
 @NRO_COMPROBANTE_HASTA as nchar(8),
 @FECHA_VENTA as date,
 @TIPO_DOCUMENTO_ID as nchar(2),
 @COMPRADOR_ID as nchar(13),
 @RAZON_SOCIAL_COMPRADOR as varchar(50),
 @CODIGO_OPERACION_ID as nchar(1),
 @TIPO_DE_CAMBIO AS NUMERIC(10,6)
 )
 
 AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @VENTA_ID NUMERIC(18,0)
	
	INSERT INTO CABECERA_VENTA 
	( EMPRESA_ID,  TIPO_COMPROBANTE_ID,  TIPO_MONEDA_ID,  PUNTO_VENTA_ID,  NRO_COMPROBANTE_DESDE,  NRO_COMPROBANTE_HASTA,   FECHA_VENTA,  TIPO_DOCUMENTO_ID,  COMPRADOR_ID,  RAZON_SOCIAL_COMPRADOR,  CODIGO_OPERACION_ID,  TIPO_DE_CAMBIO)
	VALUES 
	(@EMPRESA_ID, @TIPO_COMPROBANTE_ID, @TIPO_MONEDA_ID, @PUNTO_VENTA_ID, @NRO_COMPROBANTE_DESDE, @NRO_COMPROBANTE_HASTA, @FECHA_VENTA, @TIPO_DOCUMENTO_ID, @COMPRADOR_ID, @RAZON_SOCIAL_COMPRADOR,  @CODIGO_OPERACION_ID,  @TIPO_DE_CAMBIO)
	
	SELECT @VENTA_ID = MAX(VENTA_ID) FROM CABECERA_VENTA
	SELECT @VENTA_ID
END


;


CREATE PROCEDURE [dbo].[sp_insertConceptoCompra]
( @CODIGO VARCHAR(3), @DESCRIPCION VARCHAR(255), @DEFECTO BIT, @VISIBLE bit)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	DECLARE @ROWCONT INT
   
	INSERT INTO CONCEPTOCPA (	CODIGO, DESCRIPCION, DEFECTO, VISIBLE) VALUES(@CODIGO,@DESCRIPCION,@DEFECTO,@VISIBLE)

	
	SELECT @ROWCONT = @@ROWCOUNT
	SELECT @ROWCONT
END


;



CREATE PROCEDURE [dbo].[sp_insertConceptoVenta]
( @CODIGO VARCHAR(3), @DESCRIPCION VARCHAR(255), @DEFECTO BIT, @VISIBLE bit)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	DECLARE @ROWCONT INT
   
	INSERT INTO CONCEPTO (	CODIGO, DESCRIPCION, DEFECTO, VISIBLE) VALUES(@CODIGO,@DESCRIPCION,@DEFECTO,@VISIBLE)

	
	SELECT @ROWCONT = @@ROWCOUNT
	SELECT @ROWCONT
END



;



-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[sp_insertDetalleCompra] 
(@CABECERA_COMPRA_ID numeric(18,0), 
@CONCEPTO_ID as nchar(3),
@ALICUOTA_ID as nchar(4),
@NETO_GRAVADO money,
@EXENTO money,
@IVA money,
@TOTAL money)

AS
BEGIN
	DECLARE @ROWCONT INTEGER
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	INSERT INTO DETALLE_COMPRA 
	(   CABECERA_COMPRA_ID,  CONCEPTO_ID,  ALICUOTA_ID,  NETO_GRAVADO,  EXENTO,  IVA,  TOTAL)
	VALUES
	(  @CABECERA_COMPRA_ID, @CONCEPTO_ID, @ALICUOTA_ID, @NETO_GRAVADO, @EXENTO, @IVA, @TOTAL)
	
	SELECT @ROWCONT = @@ROWCOUNT
	SELECT @ROWCONT
END



;

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[sp_insertDetalleVenta] 
(@CABECERA_VENTA_ID numeric(18,0), 
@CONCEPTO_ID as nchar(3),
@ALICUOTA_ID as nchar(4),
@NETO_GRAVADO money,
@EXENTO money,
@IVA money,
@TOTAL money)

AS
BEGIN
	DECLARE @ROWCONT INTEGER
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	INSERT INTO DETALLE_VENTA 
	(   CABECERA_VENTA_ID,  CONCEPTO_ID,  ALICUOTA_ID,  NETO_GRAVADO,  EXENTO,  IVA,  TOTAL)
	VALUES
	(  @CABECERA_VENTA_ID, @CONCEPTO_ID, @ALICUOTA_ID, @NETO_GRAVADO, @EXENTO, @IVA, @TOTAL)
	
	SELECT @ROWCONT = @@ROWCOUNT
	SELECT @ROWCONT
END

;

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[sp_insertEmpresa] ( @IDENTIFICADOR as numeric(11,0),
								@RAZONSOCIAL varchar(255),
								@VENDEDOR as bit,
								@COMPRADOR as bit,
								@DOMICILIO as varchar(255),
								@ACTIVO as bit,
								@NONOTRIBUTISTA AS BIT)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	
	DECLARE @ROWINSERT INT

	SET NOCOUNT ON;
	
	
    -- Insert statements for procedure here
	INSERT INTO EMPRESA ( IDENTIFICADOR,  RAZONSOCIAL,  VENDEDOR,  COMPRADOR,    DOMICILIO,  ACTIVO,  MONOTRIBUTISTA)
				VALUES  (@IDENTIFICADOR, @RAZONSOCIAL, @VENDEDOR,  @COMPRADOR,  @DOMICILIO,  @ACTIVO, @NONOTRIBUTISTA)
				
	SELECT @ROWINSERT = @@ROWCOUNT
	SELECT @ROWINSERT
END

;



-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[sp_insertPercepcionCompra] 
(@CABECERA_COMPRA_ID numeric(18,0), 
@TIPO_PERCEPCION_ID as nchar(2),
@JURISDICCION_ID as nchar(2),
@IMPORTE_PERCEPCION money)

AS
BEGIN
	DECLARE @ROWCONT INTEGER
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	INSERT INTO PERCEPCION_COMPRA
	( CABECERA_COMPRA_ID,  TIPO_PERCEPCION_ID,  JURISDICCION_ID,  IMPORTE_PERCEPCION)
	VALUES
	(@CABECERA_COMPRA_ID, @TIPO_PERCEPCION_ID, @JURISDICCION_ID, @IMPORTE_PERCEPCION)
	
	SELECT @ROWCONT = @@ROWCOUNT
	SELECT @ROWCONT
END



;

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[sp_insertPuntoDeVenta]
( @EMPRESA_ID numeric(11,0), @PUNTO_VENTA varchar(5), @ACTIVO bit)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	DECLARE @ROWCONT INT
   
	INSERT INTO PUNTO_VENTA (EMPRESA_ID,PUNTO_VENTA,ACTIVO)
	VALUES(@EMPRESA_ID, @PUNTO_VENTA, @ACTIVO)

	
	SELECT @ROWCONT = @@ROWCOUNT
	SELECT @ROWCONT
END

;

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_SUBDIARIO_VENTAS_CABECERA]
(@FECHADESDE DATE =NULL , @FECHAHASTA DATE=NULL, @IDENTIFICADOR AS NUMERIC(11,0)=0)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here 
		SELECT 
	[ID. Vendedor],
	[Razon Social Vendedor],
	[Fecha de Venta],
	[Comprobante],
	[Nro. Comprobante],
	[Tipo Documento],
	[ID. Comprador],
	[Razon Social Comprador],
	[MONEDA],
	[VENTA_ID]
	FROM 
	V_SUBDIARIO_VENTAS_CABECERA  WHERE [FECHA DE VENTA] BETWEEN @FECHADESDE AND @FECHAHASTA AND [ID. Vendedor]=@IDENTIFICADOR
END

;

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE SP_SUBDIARIO_VENTAS_DETALLE
(@CABECERA_VENTA_ID AS NUMERIC(18,2) = 0)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT  * FROM dbo.V_SUBDIARIO_VENTAS_DETALLE
END

;


CREATE PROCEDURE [dbo].[sp_updateConceptoCompra] 
(@CODIGO AS VARCHAR(3), @DESCRIPCION AS VARCHAR(255),@DEFECTO BIT, @VISIBLE bit)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	DECLARE @ROWCONT INT
   
	UPDATE dbo.CONCEPTOCPA SET DESCRIPCION=@DESCRIPCION, DEFECTO=@DEFECTO, VISIBLE=@VISIBLE
	WHERE CODIGO = @CODIGO
	
	SELECT @ROWCONT = @@ROWCOUNT
	SELECT @ROWCONT
END

;



CREATE PROCEDURE [dbo].[sp_updateConceptoVenta] 
(@CODIGO AS VARCHAR(3), @DESCRIPCION AS VARCHAR(255),@DEFECTO BIT, @VISIBLE bit)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	DECLARE @ROWCONT INT
   
	UPDATE dbo.CONCEPTO SET DESCRIPCION=@DESCRIPCION, DEFECTO=@DEFECTO, VISIBLE=@VISIBLE
	WHERE CODIGO = @CODIGO
	
	SELECT @ROWCONT = @@ROWCOUNT
	SELECT @ROWCONT
END


;

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[sp_updateEmpresa]( @IDENTIFICADOR as numeric(11,0),
								@RAZONSOCIAL varchar(255),
								@VENDEDOR as bit,
								@COMPRADOR as bit,
								@DOMICILIO as varchar(255),
								@ACTIVO as bit,
								@MONOTRIBUTISTA as bit) 
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	
	DECLARE @RETORNO AS INTEGER
	
	UPDATE dbo.EMPRESA SET IDENTIFICADOR=@IDENTIFICADOR,
							RAZONSOCIAL = @RAZONSOCIAL,
							VENDEDOR = @VENDEDOR,
							COMPRADOR = @COMPRADOR,
							DOMICILIO = @DOMICILIO,
							ACTIVO = @ACTIVO,
							MONOTRIBUTISTA = @MONOTRIBUTISTA
	WHERE IDENTIFICADOR = @IDENTIFICADOR
	
	SELECT @RETORNO = @@ROWCOUNT
	SELECT @RETORNO
	
END

;

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE sp_updatePuntoDeVenta 
(@PUNTO_VENTA_ID int, @EMPRESA_ID numeric(11,0), @PUNTO_VENTA varchar(5), @ACTIVO bit)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	DECLARE @ROWCONT INT
   
	UPDATE dbo.PUNTO_VENTA SET PUNTO_VENTA = @PUNTO_VENTA,
	ACTIVO = @ACTIVO
	WHERE PUNTO_VENTA_ID = @PUNTO_VENTA_ID AND EMPRESA_ID = @EMPRESA_ID
	
	SELECT @ROWCONT = @@ROWCOUNT
	SELECT @ROWCONT
END

;

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[test] (@EMPRESA_ID as numeric(11,0))
AS
BEGIN
	select @EMPRESA_ID
END

;
